(function(g){var window=this;'use strict';var o4=function(a){a.isActive()||a.start()},Vrb=function(a,b){return b?a.captionsInitialState:"CAPTIONS_INITIAL_STATE_UNKNOWN"},Wrb=function(a,b){var c=new g.bS;
c.languageCode=a.languageCode;c.languageName=a.languageName;c.name=a.name;c.displayName=a.displayName;c.kind=a.kind;c.isDefault=!1;c.j=a.j;c.isTranslateable=a.isTranslateable;c.vssId=a.vssId;c.url=a.url;c.translationLanguage=b;a.xtags&&(c.xtags=a.xtags);a.captionId&&(c.captionId=a.captionId);return c},Xrb=function(a,b){var c,d,e;
return g.G(function(f){if(f.j==1)return c=a+"|"+b,g.z(f,g.JC(),2);if(f.j!=3){d=f.B;if(!d)throw g.mC("gct");return g.z(f,g.qS(d),3)}e=f.B;return f.return(e.get("captions",c))})},Yrb=function(a,b,c){Xrb(a,b).then(function(d){d&&c(d.trackData,new g.bS(d.metadata))})},asb=function(a){if(!Zrb.test(a))throw Error("'"+a+"' is not a valid hex color");
a.length==4&&(a=a.replace($rb,"#$1$1$2$2$3$3"));a=a.toLowerCase();a=parseInt(a.slice(1),16);return[a>>16,a>>8&255,a&255]},bsb=function(){return g.GB("yt-player-caption-display-settings")},p4=function(){this.segments=[]},csb=function(a,b){var c=g.Sb(a.segments,b);
c>=0||c<0&&(-c-1)%2===1||(c=-c-1,c>0&&b-a.segments[c-1]===1&&c<a.segments.length&&a.segments[c]-b===1?(g.Gb(a.segments,c),g.Gb(a.segments,c-1)):c>0&&b-a.segments[c-1]===1?a.segments[c-1]=b:c<a.segments.length&&a.segments[c]-b===1?a.segments[c]=b:(g.Ob(a.segments,c,0,b),g.Ob(a.segments,c+1,0,b)))},dsb=function(a,b,c,d,e,f){g.I.call(this);
this.policy=a;this.player=b;this.qa=c;this.Z=d;this.G=e;this.Y=f;this.D=new p4;this.K=-1;this.C=this.B=this.j=null;this.N=new g.Lv(this.PZ,1E3,this);this.events=new g.SJ(this);g.M(this,this.N);g.M(this,this.events);this.events.T(b,"SEEK_COMPLETE",this.wB);this.wB();this.PZ()},esb=function(a){return a.j&&a.j.D?a.j.D+a.player.Mc()<a.player.getCurrentTime():!1},fsb=function(a,b){var c=g.OSa(b,a.policy,{}).Ke(),d={format:"RAW",
withCredentials:!0};if(a.policy.Ha){d.method="POST";var e=b.D,f=(0,g.gZ)([120,0]);e&&g.$N(e,g.AQa);d.postBody=f}a.G&&(d.responseType="arraybuffer");a.C=g.SA(c,d,3,100).then(function(h){a:{h=h.xhr;a.Ma();if(a.B){var l=!(a.G?h.response:h.responseText)||h.status>=400,m=g.wTa(h);if(m){h=g.OSa(a.B,a.policy,{});a.B.il(h,m);fsb(a,a.B);break a}l?a.player.ma("capfail",{status:h.status}):(a.player.Ei().gj("fcb_r"),m=a.B.jb[0].Pa,a.Z!=null&&a.K!==m&&(l=a.B.jb[0],a.G?a.Z(h.response,(l.startTime+a.player.Mc())*
1E3):a.Z(h.responseText,(l.startTime+a.player.Mc())*1E3),a.K=m))}a.B=null;a.C=null}}).Fl(function(h){a.B=null;
a.C=null;var l;a.player.ma("capfail",{status:(l=h.xhr)==null?void 0:l.status})});
a.B=b;csb(a.D,a.B.jb[0].Pa)},q4=function(a,b){g.sV.call(this,b.U());
this.j=a;this.J=b;this.C=null;this.G=!1;this.K=g.AI(this.J.U())&&!this.j.isManifestless},hsb=function(a,b){var c=[],d;
for(d in a.j.j)if(a.j.j.hasOwnProperty(d)){var e=a.j.j[d];if(g.g0a(e,b||null)){var f=e.info.id,h=f,l="."+f,m="",n="",p="";if(e=e.info.captionTrack)f=e.languageCode,h=e.displayName,l=e.vssId,m=e.kind,a.J.U().L("html5_expose_xtags_through_caption_track")&&(n=e.xtags),p=e.id;else{e=f;var q=g.Vpb.get(e);q==null&&(q=gsb[e]||gsb[e.replace(/-/g,"_")],g.Vpb.set(e,q));h=q||h}c.push(new g.bS({id:d,languageCode:f,languageName:h,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:l,kind:m,xtags:n,captionId:p}))}}return c},
isb=function(a,b){return b!=null&&b in a.j.j?a.j.j[b]:null},jsb=function(a,b,c){var d=[],e;
for(e in a.j.j)if(a.j.j.hasOwnProperty(e)){var f=a.j.j[e];if(g.g0a(f,c||null)){var h=f.info.captionTrack;h&&h.languageCode===b&&d.push(f)}}return d.length?d[0]:null},ksb=function(){var a=void 0;
a=a===void 0?{}:a;var b="suggest_correction"in g.hqb?g.hqb.suggest_correction:"Edit caption";b=b||"";var c={},d;for(d in a){c={DF:c.DF};c.DF=d;var e=function(f){return function(){return String(a[f.DF])}}(c);
b=b.replace(new RegExp("\\$\\{"+c.DF+"\\}","gi"),e);b=b.replace(new RegExp("\\$"+c.DF,"gi"),e)}return b},r4=function(a,b,c,d,e,f,h,l,m,n){var p=n.isInline()&&!0,q={};
Object.assign(q,b);Object.assign(q,a.params);Object.assign(q,c);var r={};Object.assign(r,b.Re);a.params.Re&&Object.assign(r,a.params.Re);Object.assign(r,c.Re);p&&(q.windowOpacity=.6,r.backgroundOpacity=0);q.Re=r;var t=q.Ki===1,u=[{I:"span",S:"captions-text",W:{style:"word-wrap: normal; display: block;"}}],w,A,C;(l=l.gb("caption_edit_on_hover")&&((w=n.getVideoData().getPlayerResponse())==null?void 0:(A=w.captions)==null?void 0:(C=A.playerCaptionsTracklistRenderer)==null?void 0:C.openTranscriptCommand))&&
u.unshift({I:"button",S:"caption-edit",W:{tabindex:"0","aria-label":ksb()},V:[{I:"svg",W:{fill:"#e3e3e3",height:"100%",viewBox:"5 5 38 38",width:"100%"},V:[{I:"path",W:{d:"M9 39h2.2l24.25-24.25-1.1-1.1-1.1-1.1L9 36.8Zm-3 3v-6.4L35.4 6.2q.85-.85 2.12-.82 1.27.02 2.12.87L41.8 8.4q.85.85.85 2.1t-.85 2.1L12.4 42Zm33.5-31.55L37.45 8.4Zm-4.05 4.3-1.1-1.1-1.1-1.1 2.2 2.2Z"}}]}]});g.W.call(this,{I:"div",S:"caption-window",W:{id:"caption-window-"+a.id,dir:t?"rtl":"ltr",tabindex:"0",lang:q.lang},V:u});var F=
this;this.K=[];this.Ha=!1;this.B=a;this.Na=this.La=null;this.playerWidth=f;this.playerHeight=h;this.N=null;this.maxWidth=f*.96;this.maxHeight=h*.96;this.j=q;this.Ac=c;this.ra=b;this.D=this.Ga("captions-text");this.Ob=this.D.style.getPropertyValue("box-decoration-break")!==""||this.D.style.getPropertyValue("-webkit-box-decoration-break")!=="";this.Va=lsb(d,e,f,h);this.vc=m;l&&(this.G=this.Ga("caption-edit"),this.T(this.G,"click",function(){F.vc()}));
this.type=0;this.eb=this.Va*msb(r);this.Gb=p;a=new g.OU(this.element,!0);g.M(this,a);a.subscribe("dragstart",this.S4,this);a.subscribe("dragmove",this.R4,this);a.subscribe("dragend",this.Q4,this);this.fb=this.bb=this.Eb=this.rb=0;a="";this.j.windowOpacity&&(a=asb(this.j.windowColor),a="rgba("+a[0]+","+a[1]+","+a[2]+","+this.j.windowOpacity+")");b={"background-color":a,display:this.j.isVisible===!1?"none":"","text-align":nsb[this.j.textAlign]};this.Ob&&(b["border-radius"]=a?this.eb/8+"px":"");(this.C=
this.B.params.Ki===2||this.B.params.Ki===3)&&osb(this,this.element);g.Ns(this.element,b);if(p){var H;(H=this.element.parentElement)==null||H.style.setProperty("--caption-window-color",a)}switch(this.j.mm){case 0:case 1:case 2:g.Sv(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.Sv(this.element,"ytp-caption-window-bottom")}},osb=function(a,b){var c="vertical-rl";
a.j.JT===1&&(c="vertical-lr");g.Ps&&(c=c==="vertical-lr"?"tb-lr":"tb-rl");g.Ns(b,"-o-writing-mode",c);g.Ns(b,"-webkit-writing-mode",c);g.Ns(b,"writing-mode",c);g.Ns(b,"text-orientation","upright");g.Sv(b,"ytp-vertical-caption");a.B.params.Ki===3&&(g.Ns(b,"text-orientation",""),g.Ns(b,"transform","rotate(180deg)"))},msb=function(a){var b=1+.25*(a.fontSizeIncrement||0);
if(a.offset===0||a.offset===2)b*=.8;return b},psb=function(a,b){var c={},d=b.background?b.background:a.j.Re.background;
if(b.backgroundOpacity!=null||b.background){var e=b.backgroundOpacity!=null?b.backgroundOpacity:a.j.Re.backgroundOpacity;d=asb(d);c.background="rgba("+d[0]+","+d[1]+","+d[2]+","+e+")";a.Ob&&(c["box-decoration-break"]="clone",c["border-radius"]=a.eb/8+"px")}if(b.fontSizeIncrement!=null||b.offset!=null)c["font-size"]=a.Va*msb(b)+"px";d=1;e=b.color||a.j.Re.color;if(b.color||b.textOpacity!=null)e=asb(e),d=b.textOpacity==null?a.j.Re.textOpacity:b.textOpacity,e="rgba("+e[0]+","+e[1]+","+e[2]+","+d+")",
c.color=e,c.fill=e;var f=b.charEdgeStyle;f===0&&(f=void 0);if(f){e="rgba(34, 34, 34, "+d+")";var h="rgba(204, 204, 204, "+d+")";b.pO&&(h=e=b.pO);var l=a.Va/16/2,m=Math.max(l,1),n=Math.max(2*l,1),p=Math.max(3*l,1),q=Math.max(5*l,1);d=[];switch(f){case 4:for(;p<=q;p+=l)d.push(n+"px "+n+"px "+p+"px "+e);break;case 1:n=window.devicePixelRatio>=2?.5:1;for(f=m;f<=p;f+=n)d.push(f+"px "+f+"px "+e);break;case 2:d.push(m+"px "+m+"px "+h);d.push("-"+m+"px -"+m+"px "+e);break;case 3:for(p=0;p<5;p++)d.push("0 0 "+
n+"px "+e)}c["text-shadow"]=d.join(", ")}e="";switch(b.fontFamily){case 1:e='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:e='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:e='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:e='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:e='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:e=g.bB()?
'"Carrois Gothic SC", sans-serif-smallcaps':'"Arial Unicode Ms", Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:e='"YouTube Noto", Roboto, "Arial Unicode Ms", Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}e&&(c["font-family"]=e);e=b.offset;e==null&&(e=a.j.Re.offset);switch(e){case 0:c["vertical-align"]="sub";break;case 2:c["vertical-align"]="super"}b.fontFamily===7&&(c["font-variant"]="small-caps");b.bold&&(c["font-weight"]="bold");b.italic&&(c["font-style"]=
"italic");b.underline&&(c["text-decoration"]="underline");b.P9&&(c.visibility="hidden");b.aZ===1&&a.C&&(c["text-combine-upright"]="all",c["text-orientation"]="mixed",e=g.PR||g.lC,a.B.params.Ki===3?c.transform=e?"rotate(90deg)":"rotate(180deg)":e&&(c.transform="rotate(-90deg)"));if(b.So===1||b.So===2||b.So===3||b.So===4||b.So===5)if(g.PR)c["font-weight"]="bold";else switch(c["text-emphasis-style"]="filled circle",c["text-emphasis-color"]="currentcolor",c["webkit-text-emphasis"]="filled circle",b.So){case 4:case 3:c["text-emphasis-position"]=
"under left";c["webkit-text-emphasis-position"]="under left";break;case 5:case 2:c["text-emphasis-position"]="over right",c["webkit-text-emphasis-position"]="over right"}return c},s4=function(a){a=a.split("px");
return a.length>0?(a=Number(a[0]))?a:0:0},qsb=function(a){a.N=g.yf("SPAN");
g.Ns(a.N,{display:"block"});g.Sv(a.N,"caption-visual-line");a.D.appendChild(a.N)},rsb=function(a,b){var c=g.yf("SPAN");
g.Ns(c,{display:"inline-block","white-space":"pre-wrap"});g.Ns(c,psb(a,b));c.classList.add("ytp-caption-segment");a.N.appendChild(c);c.previousElementSibling&&(g.Ns(c.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.Ns(c,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return c},ssb=function(a,b,c){a.Ha=a.Ha||!!c;
var d={};Object.assign(d,a.j.Re);Object.assign(d,c||b.j);Object.assign(d,a.Ac.Re);(c=!a.N)&&qsb(a);for(var e=a.La&&a.Na&&g.id(d,a.Na)?a.La:rsb(a,d),f=typeof b.text==="string",h=f?b.text.split("\n"):[b.text],l=0;l<h.length;l++){var m=l>0||!b.append,n=h[l];m&&!c?(qsb(a),e=rsb(a,d)):m&&c&&(c=!1);n&&(e.appendChild(f?g.zf(n):n),f||n.tagName!=="RUBY"||n.childElementCount!==4||g.PR||!g.Qs(n.children[2],"text-emphasis")||(m=a.C?"padding-right":"padding-top",g.Qs(n.children[2],"text-emphasis-position")&&(m=
a.C?"padding-left":"padding-bottom"),g.Pc?g.Ns(e,m,"1em"):g.Ns(e,m,"0.5em")))}a.Na=d;a.La=e;a.K.push(b)},lsb=function(a,b,c,d){var e=b/360*16;
b>=a&&(a=640,d>c*1.3&&(a=480),e=c/a*16);return e},usb=function(){this.C=this.time=this.mode=this.B=0;
this.D=new tsb(this);this.G=new tsb(this);this.j=[];this.clear()},wsb=function(a,b,c){if(a===255&&b===255||!a&&!b)return{jw:a,
Zs:b,result:0};a=vsb[a];b=vsb[b];if(a&128){var d;if(d=!(b&128))d=b,d=c.qe()&&c.Zs===d;if(d)return{jw:a,Zs:b,result:1}}else if(b&128&&1<=a&&a<=31)return{jw:a,Zs:b,result:2};return{jw:a,Zs:b,result:3}},ysb=function(a,b,c,d){b===255&&c===255||!b&&!c?(++a.C===45&&a.reset(),a.D.B.clear(),a.G.B.clear()):(a.C=0,xsb(a.D,b,c,d))},zsb=function(a,b){a.j.sort(function(e,f){var h=e.time-f.time;
return h===0?e.order-f.order:h});
for(var c=g.v(a.j),d=c.next();!d.done;d=c.next())d=d.value,a.time=d.time,d.type===0?ysb(a,d.dX,d.eX,b):d.type===1&&a.B&496&&xsb(a.G,d.dX,d.eX,b);a.j.length=0},t4=function(){this.type=0},u4=function(){this.state=this.Zs=this.jw=0},Asb=function(){this.timestamp=this.j=0},v4=function(a){this.D=a;
this.B=[];this.j=this.col=this.row=0;this.style=new t4;for(a=this.C=0;a<=15;a++){this.B[a]=[];for(var b=0;b<=32;b++)this.B[a][b]=new Asb}},w4=function(a,b){if(a.style.type===3){for(var c=0,d=0,e=a.D.time+0,f="",h="",l=e,m=1;m<=15;++m){for(var n=!1,p=d?d:1;p<=32;++p){var q=a.B[m][p];
if(q.j!==0){c===0&&(c=m,d=p);n=String.fromCharCode(q.j);var r=q.timestamp;r<e&&(e=r);q.timestamp=l;h&&(f+=h,h="");f+=n;n=!0}if((q.j===0||p===32)&&n){h="\n";break}else if(d&&!n)break}if(c&&!n)break}f&&b.D(c,d,e,l,f)}else for(d=c=0,f=e=a.D.time+0,h=1;h<=15;++h)for(l="",m=1;m<=32;++m)if(p=a.B[h][m],q=p.j,q!==0&&(c===0&&(c=h,d=m),n=String.fromCharCode(q),r=p.timestamp,r<=e&&(e=r),l+=n,p.reset()),m===32||q===0)l&&b.D(c,d,e,f,l),e=f,l="",d=c=0},Fsb=function(a,b){switch(a){case 0:return Bsb[(b&127)-32];
case 1:return Csb[b&15];case 2:return Dsb[b&31];case 3:return Esb[b&31]}return 0},x4=function(a){return a.B[a.row][a.col]},y4=function(a,b,c){b>=2&&a.col>1&&(--a.col,x4(a).j=0);
var d=x4(a);d.timestamp=a.D.time+0;d.j=Fsb(b,c);a.col<32&&a.col++},Gsb=function(a,b,c,d){for(var e=0;e<d;e++)for(var f=0;f<=32;f++){var h=a.B[b+e][f],l=a.B[c+e][f];
h.j=l.j;h.timestamp=l.timestamp}},z4=function(a,b,c){for(var d=0;d<c;d++)for(var e=0;e<=32;e++)a.B[b+d][e].reset()},Hsb=function(a){a.row=a.j>0?a.j:1;
a.col=1;z4(a,0,15)},Isb=function(a){this.C=a;
this.G=0;this.style=new t4;this.K=new v4(this.C);this.N=new v4(this.C);this.text=new v4(this.C);this.B=this.K;this.D=this.N;this.j=this.B},Jsb=function(a,b,c){var d=a.B,e=!1;
switch(a.style.get()){case 4:case 1:case 2:a.style.get()===4&&d.j>0||(w4(d,c),Hsb(a.B),Hsb(a.D),d.row=15,d.j=b,e=!0)}a.style.set(3);a.j=d;a.j.style=a.style;a.C.mode=1<<d.C;e?d.col=1:d.j!==b&&(d.j>b?(w4(d,c),z4(d,d.row-d.j,b)):d.row<b&&(b=d.j),d.j=b)},Ksb=function(a){a.style.set(1);
a.j=a.D;a.j.j=0;a.j.style=a.style;a.C.mode=1<<a.j.C},Lsb=function(a){a.style.set(4);
a.j=a.text;a.j.style=a.style;a.C.mode=1<<a.j.C},tsb=function(a){this.j=a;
this.G=0;this.C=new Isb(this.j);this.K=new Isb(this.j);this.B=new u4;this.D=this.C},xsb=function(a,b,c,d){a.B.update();
b=wsb(b,c,a.B);switch(b.result){case 0:return;case 1:case 2:return}var e=b.jw;c=b.Zs;if(32<=e||!e)a.j.mode&a.j.B&&(b=e,b&128&&(b=127),c&128&&(c=127),a=a.D.j,b&96&&y4(a,0,b),c&96&&y4(a,0,c),b!==0&&c!==0&&a.style.type===3&&w4(a,d));else if(e&16)a:if(!a.B.matches(e,c)&&(b=a.B,b.jw=e,b.Zs=c,b.state=2,b=e&8?a.K:a.C,a.D=b,a.j.mode=1<<(a.G<<2)+(b.G<<1)+(b.style.type===4?1:0),(a.j.mode|1<<(a.G<<2)+(b.G<<1)+(b.style.type!==4?1:0))&a.j.B))if(c&64){d=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(e&7)<<1|c>>5&1];
a=c&16?((c&14)>>1)*4:0;c=b.j;switch(b.style.get()){case 4:d=c.row;break;case 3:if(d!==c.row){if(d<c.j&&(d=c.j,d===c.row))break;var f=1+c.row-c.j,h=1+d-c.j;Gsb(c,h,f,c.j);b=f;e=c.j;h<f?(f=h+e-f,f>0&&(b+=f,e-=f)):(f=f+e-h,f>0&&(e-=f));z4(c,b,e)}}c.row=d;c.col=a+1}else switch(e&7){case 1:switch(c&112){case 32:y4(b.j,0,32);break a;case 48:c===57?(d=b.j,x4(d).j=0,d.col<32&&d.col++):y4(b.j,1,c&15)}break;case 2:c&32&&y4(b.j,2,c&31);break;case 3:c&32&&y4(b.j,3,c&31);break;case 4:case 5:if(32<=c&&c<=47)switch(c){case 32:Ksb(b);
break;case 33:d=b.j;d.col>1&&(--d.col,x4(d).j=0);break;case 36:d=b.j;b=x4(d);for(a=0;a<=15;a++)for(c=0;c<=32;c++)if(d.B[a][c]===b){for(;c<=32;c++)d.B[a][c].reset();break}break;case 37:Jsb(b,2,d);break;case 38:Jsb(b,3,d);break;case 39:Jsb(b,4,d);break;case 40:y4(b.j,0,32);break;case 41:b.style.set(2);b.j=b.B;b.j.j=0;b.j.style=b.style;b.C.mode=1<<b.j.C;break;case 42:d=b.text;d.j=15;d.style.set(4);Hsb(d);Lsb(b);break;case 43:Lsb(b);break;case 44:a=b.B;switch(b.style.get()){case 1:case 2:case 3:w4(a,
d)}z4(a,0,15);break;case 45:b:{a=b.j;switch(b.style.get()){default:case 2:case 1:break b;case 4:if(a.row<15){++a.row;a.col=1;break b}break;case 3:}a.j<2&&(a.j=2,a.row<a.j&&(a.row=a.j));b=a.row-a.j+1;w4(a,d);Gsb(a,b,b+1,a.j-1);z4(a,a.row,1)}break;case 46:z4(b.D,0,15);break;case 47:w4(b.B,d),b.D.updateTime(b.C.time+0),d=b.D,b.D=b.B,b.B=d,Ksb(b)}break;case 7:switch(c){case 33:case 34:case 35:d=b.j,(d.col+=c&3)>32&&(d.col=32)}}},Msb=function(){},A4=function(a,b,c,d,e,f,h){f=f===void 0?!1:f;
h=h===void 0?null:h;g.XI.call(this,a,a+b,{priority:c,namespace:"captions"});this.windowId=d;this.text=e;this.append=f;this.j=h},Osb=function(a,b,c,d,e,f,h){var l=f[0],m=h[l.getAttribute("p")];
if(m.eg===1){var n=f[1],p=f[2];f=f[3];l.getAttribute("t");n.getAttribute("t");p.getAttribute("t");f.getAttribute("t");l.getAttribute("p");n.getAttribute("p");f.getAttribute("p");h=h[p.getAttribute("p")];l=Nsb(l.textContent,n.textContent,p.textContent,f.textContent,h);return new A4(a,b,e,c,l,d,m)}switch(m.eg){case 9:case 10:m.So=1;break;case 11:m.So=2;break;case 12:m.So=3;break;case 13:m.So=4;break;case 14:m.So=5}return new A4(a,b,e,c,l.textContent||"",d,m)},Nsb=function(a,b,c,d,e){var f=g.bB(),h=
f?g.yf("DIV"):g.yf("RUBY"),l=g.yf("SPAN");
l.textContent=a;h.appendChild(l);a=f?g.yf("DIV"):g.yf("RP");a.textContent=b;h.appendChild(a);b=f?g.yf("DIV"):g.yf("RT");b.textContent=c;h.appendChild(b);c=e.eg;if(c===10||c===11||c===12||c===13||c===14)if(g.Ns(b,"text-emphasis-style","filled circle"),g.Ns(b,"text-emphasis-color","currentcolor"),g.Ns(b,"webkit-text-emphasis","filled circle"),e.eg===11||e.eg===13)g.Ns(b,"webkit-text-emphasis-position","under left"),g.Ns(b,"text-emphasis-position","under left");c=!0;if(e.eg===4||e.eg===7||e.eg===12||
e.eg===14)g.Ns(h,"ruby-position","over"),g.Ns(h,"-webkit-ruby-position","before");else if(e.eg===5||e.eg===6||e.eg===11||e.eg===13)g.Ns(h,"ruby-position","under"),g.Ns(h,"-webkit-ruby-position","after"),c=!1;e=f?g.yf("DIV"):g.yf("RP");e.textContent=d;h.appendChild(e);f&&(d=c,g.Ns(h,{display:"inline-block",position:"relative"}),f=h.firstElementChild.nextElementSibling,g.Ns(f,"display","none"),f=f.nextElementSibling,g.Ns(f,{"font-size":"0.5em","line-height":"1.2em","text-align":"center",position:"absolute",
left:"50%",transform:"translateX(-50%)",width:"400%"}),g.Ns(h.lastElementChild,"display","none"),d?(g.Ns(h,"padding-top","0.6em"),g.Ns(f,"top","0")):(g.Ns(h,"padding-bottom","0.6em"),g.Ns(f,"bottom","0")));return h},B4=function(){g.I.apply(this,arguments)},C4=function(a,b,c,d,e){g.XI.call(this,a,a+b,{priority:c,
namespace:"captions"});this.id=d;this.params=e;this.j=[]},Psb=function(a){var b="_"+D4++;
return new C4(0,0x8000000000000,0,b,a)},E4=function(a){B4.call(this);
this.C=a;this.pens={};this.N={};this.Z={};this.D="_"+D4++;this.K={};this.B=this.j=null;this.G=!0},F4=function(a,b){a=a.getAttribute(b);
if(a!=null)return Number(a)},G4=function(a,b){a=a.getAttribute(b);
if(a!=null)return a==="1"},H4=function(a,b){a=F4(a,b);
return a!==void 0?a:null},J4=function(a,b){a=a.getAttribute(b);
if(a!=null)return I4.test(a),a},Qsb=function(a,b){var c={},d=b.getAttribute("ws");
Object.assign(c,d?a.Z[d]:a.C);a=H4(b,"mh");a!=null&&(c.jB=a);a=H4(b,"ju");a!=null&&(c.textAlign=a);a=H4(b,"pd");a!=null&&(c.Ki=a);a=H4(b,"sd");a!=null&&(c.JT=a);a=J4(b,"wfc");a!=null&&(c.windowColor=a);b=F4(b,"wfo");b!==void 0&&(c.windowOpacity=b/255);return c},Rsb=function(a,b){var c={},d=b.getAttribute("wp");
d&&Object.assign(c,a.N[d]);a=H4(b,"ap");a!=null&&(c.mm=a);a=F4(b,"cc");a!=null&&(c.ut=a);a=F4(b,"ah");a!=null&&(c.pk=a);a=F4(b,"rc");a!=null&&(c.ws=a);b=F4(b,"av");b!=null&&(c.Uo=b);return c},Ssb=function(a,b,c,d){var e={};
Object.assign(e,Rsb(a,b));Object.assign(e,Qsb(a,b));d?g.id(e,a.C)?(d=a.D,e=a.C):d="_"+D4++:d=b.getAttribute("id")||"_"+D4++;a=F4(b,"t")+c;b=F4(b,"d")||0x8000000000000;if(e.Ki===2||e.Ki===3)c=e.ws,e.ws=e.ut,e.ut=c;return new C4(a,b,0,d,e)},K4=function(a){B4.call(this);
this.G=a;this.j=new Map;this.C=new Map;this.D=new Map;this.B=new Map},L4=function(a){a=g.ze(Math.round(a),0,16777215).toString(16).toUpperCase();
return"#000000".substr(0,7-a.length)+a},Tsb=function(a,b,c,d,e){d===0&&(d=0x8000000000000);
var f={};b.wpWinPosId&&Object.assign(f,a.C.get(b.wpWinPosId));b.wsWinStyleId&&Object.assign(f,a.D.get(b.wsWinStyleId));a=b.rcRowCount;a!==void 0&&(f.ws=a);b=b.ccColCount;b!==void 0&&(f.ut=b);if(f.Ki===2||f.Ki===3)b=f.ws,f.ws=f.ut,f.ut=b;return new C4(c,d,0,e,f)},M4=function(a,b,c,d){g.sV.call(this,a);
this.videoData=b;this.audioTrack=c;this.Ua=d;this.D=b.Gv},N4=function(a,b,c,d,e,f,h,l,m,n){r4.call(this,a,b,c,d,e,f,h,l,m,n);
this.type=1},O4=function(a,b,c){this.trackData=a;
this.K=c;this.version=this.G=this.C=this.byteOffset=0;this.j=new DataView(this.trackData);this.B=[]},P4=function(a){var b=a.byteOffset;
a.byteOffset+=1;return a.j.getUint8(b)},Q4=function(a){var b=a.byteOffset;
a.byteOffset+=4;return a.j.getUint32(b)},R4=function(a,b){B4.call(this);
this.B=a;this.C=b;this.track=this.C.languageName==="CC3"?4:0;this.j=new usb;this.j.B=1<<this.track},Vsb=function(a){if(typeof a==="string")return!1;
a=new O4(a,8,0);return Usb(a)},Usb=function(a){if(!(a.byteOffset<a.j.byteLength)||Q4(a)!==1380139777)return!1;
a.version=P4(a);if(a.version>1)return!1;P4(a);P4(a);P4(a);return!0},S4=function(a,b,c,d,e,f,h,l,m,n){r4.call(this,a,b,c,d,e,f,h,l,m,n);
var p=this;this.type=2;this.Ca=[];this.qa=this.Y=this.Sa=0;this.Fa=NaN;this.Kb=0;this.Sb=null;this.Wa=new g.Lv(this.Qba,433,this);this.G&&(n.createClientVe(this.G,this,167342),this.T(this.G,"click",function(){n.logClick(p.G)}),a=new g.OU(this.element,!0),g.M(this,a),a.subscribe("hoverstart",function(){n.logVisibility(p.G,!0)},this));
g.Sv(this.element,"ytp-caption-window-rollup");g.M(this,this.Wa);g.Ns(this.element,"overflow","hidden")},Wsb=function(a,b){if(!b)return"";
a.C&&a.B.params.JT!==1&&(b*=-1);return"translate"+(a.C?"X":"Y")+"("+b+"px)"},Xsb=function(a){a.Ca=Array.from(document.getElementsByClassName("caption-visual-line"));
for(var b=a.B.params.ws,c=0,d=0,e=a.Ca.length-1;c<b&&e>-1;){var f=a.Ca[e];d+=a.C?f.offsetWidth:f.offsetHeight;c++;e--}a.Y=d;b=Math;c=b.max;isNaN(a.Fa)&&((d=a.j.ut)?(e=g.yf("SPAN"),g.Kf(e,"\u2013".repeat(d)),g.Ns(e,psb(a,a.j.Re)),a.D.appendChild(e),a.Fa=e.offsetWidth,a.D.removeChild(e)):a.Fa=0);d=a.D;a.qa=c.call(b,a.Fa,a.Kb,(a.C?d.offsetHeight:d.offsetWidth)+1)},Ysb=function(a,b){Xsb(a);
var c=a.Ca.reduce(function(f,h){return(a.C?h.offsetWidth:h.offsetHeight)+f},0);
c=a.Y-c;if(c!==a.Sa){var d=c>0&&a.Sa===0,e=c<a.Sa;b||isNaN(c)||d||!e||(g.Sv(a.element,"ytp-rollup-mode"),g.Mv(a.Wa));g.Ns(a.D,"transform",Wsb(a,c));a.Sa=c}Xsb(a)},T4=function(){B4.call(this)},Zsb=function(a,b,c,d,e,f,h,l,m){switch(h.tagName){case "b":l.bold=!0;
break;case "i":l.italic=!0;break;case "u":l.underline=!0}for(var n=0;n<h.childNodes.length;n++){var p=h.childNodes[n];if(p.nodeType===3)p=new A4(b,c,d,e.id,p.nodeValue,f||n>0,g.gd(l)?void 0:l),m.push(p),e.j.push(p);else{var q={};Object.assign(q,l);Zsb(a,b,c,d,e,!0,p,q,m)}}},$sb=function(a){var b=a.split(":");
a=0;b=g.v(b);for(var c=b.next();!c.done;c=b.next())a=a*60+Number(c.value);return a*1E3},atb=function(a,b,c,d){d=Object.assign({jB:0},d);
return new C4(a,b,c,"_"+D4++,d)},U4=function(a,b){g.I.call(this);
this.J=a;this.X=b;this.j=null;this.B=this.J.jA()},btb=function(a){if(typeof a==="string"||Vsb(a))return a;
var b=new DataView(a);if(b.byteLength<=8||b.getUint32(4)!==1718909296)return"";b=g.FP(b,0,1835295092);if(!b||!b.size)return"";a=new Uint8Array(a,b.dataOffset,b.size-(b.dataOffset-b.offset));return g.FN(a)},dtb=function(a,b,c){if(typeof b==="string"||Vsb(b))return[{trackData:b,
CT:c}];var d=new DataView(b);if(d.byteLength<=8||d.getUint32(4)!==1718909296)return[];var e=g.cSa(d);if(a.B&&e){var f=g.URa(e),h=g.VRa(e);e=e.cj;f&&e&&a.B.IH(e,f,h)}a=g.MP(d,1835295092);if(!a||!a.length||!a[0].size)return[];f=[];for(h=0;h<a.length;h++)e=a[h],e=new Uint8Array(b,e.dataOffset,e.size-(e.dataOffset-e.offset)),e=g.FN(e),f.push({trackData:e,CT:c+h*1E3});ctb(d,f,c);return f=f.filter(function(l){return!!l.trackData})},ctb=function(a,b,c){var d=g.FP(a,0,1836476516),e=9E4;
d&&(e=g.GP(d)||9E4);d=0;for(var f=g.MP(a,1836019558),h=0;h<f.length;h++){var l=f[h];h<b.length&&(l=g.FP(a,l.dataOffset,1953653094))&&(l=g.FP(a,l.dataOffset,1952867444))&&(l=g.$Ra(l)/e*1E3,h===0&&(d=l),b[h].CT=l-d+c||c*h*1E3)}},etb=function(a,b,c,d,e){if(!Vsb(c))throw Error("Invalid binary caption track data");
a.j||(a.j=new R4(e,b));return a.j.Io(c,d)},ftb=function(a,b,c){a.j||(a.j=new T4);
a=a.j.Io(b,c);Math.random()<.01&&g.vE(Error("Deprecated subtitles format in web player: WebVTT"));return a},htb=function(a,b,c,d){if(c[0]==="{")try{return a.j||(a.j=new K4(gtb(b))),a.j.Io(c,d)}catch(f){return g.uE(f),[]}var e=g.e2(c);
if(!e||!e.firstChild)throw a=Error("Invalid caption track data"),a.params=c,a;if(e.firstChild.tagName==="timedtext"){if(Number(e.firstChild.getAttribute("format"))===3)return a.j||(a.j=new E4(gtb(b),a.X)),a.j.Io(e,d);a=Error("Unsupported subtitles format in web player (Format2)");a.params=c;throw a;}if(e.firstChild.tagName==="transcript")throw a=Error("Unsupported subtitles format in web player (Format1)"),a.params=c,a;a=Error("Invalid caption track data");a.params=c;throw a;},gtb=function(a){var b=
{};
if(a=g.eS(a))b.lang=a,g.fmb.test(a)&&(b.Ki=1);return b},V4=function(a){g.pV.call(this,a);
var b=this;this.J=a;this.X=this.J.U();this.videoData=this.J.getVideoData();this.Eb=this.J.ob();var c;this.fb=(c=this.J.getVideoData(1))==null?void 0:g.oT(c);this.C={Re:{}};this.G={Re:{}};this.Ha=[];this.ra={};this.Va={};this.Y=!1;this.Ob=g.pT(this.videoData);this.bb=g.h0a(this.videoData,this.J);this.Kb=!!this.videoData.captionTracks.length;this.Sb=!!this.videoData.ke;this.Wa=this.X.controlsType==="3";this.j=this.N=this.Z=this.Sa=this.rb=null;this.eb=new U4(this.J,this.X);this.B=null;this.Ca=new g.SJ(this);
this.K=new g.W({I:"div",S:"ytp-caption-window-container",W:{id:"ytp-caption-window-container"}});this.qa={top:0,right:0,bottom:0,left:0,width:1,height:1};c=null;var d=g.rw("yt-html5-player-modules::subtitlesModuleData");d&&(c=new g.jw(d));this.storage=c;var e;this.Jb=!((e=a.Je())==null||!e.yH());this.D=itb(this);this.Fa=!this.D&&this.Wa&&this.Jb&&this.bb;g.M(this,this.eb);this.D?this.Na=this.La=null:(this.La=new g.Kv(this.ZT,void 0,this),g.M(this,this.La),this.Na=new g.Lv(this.qda,2E3,this),g.M(this,
this.Na));g.M(this,this.Ca);g.QT(this.player,this.K.element,4);g.M(this,this.K);this.D||this.Ca.T(a,"resize",this.cU);(this.Gb=g.AR(this.X)&&!g.rB()&&!this.J.isFullscreen()&&!this.D&&!this.Fa)&&this.Ca.T(a,"resize",this.Xaa);this.Ca.T(a,"onPlaybackAudioChange",this.naa);this.Ca.T(a,g.YI("captions"),function(f){b.onCueRangeEnter(f)});
this.Ca.T(a,g.ZI("captions"),function(f){b.onCueRangeExit(f)});
this.fb&&this.Ca.T(a,"videodatachange",function(f,h){b.onVideoDataChange(f,h)});
jtb(this,bsb()||{});this.player.Dc("onCaptionsModuleAvailable")},mtb=function(a){if(a.X.Jb===1||a.videoData.SH===1||g.YS(a.videoData,"yt:cc")==="alwayson")return!0;
if(a.videoData.captionTracks.length)var b=a.getAudioTrack().B;if(a.X.Jb===2){if(g.MR(a.X))var c=ktb(a);else if(a.storage)try{c=a.storage.get("module-enabled")}catch(e){a.storage.remove("module-enabled")}else c=null;if(c!=null)return!!c}c=Vrb(a.player.getAudioTrack(),g.MR(a.X));var d=g.YS(a.videoData,"yt:cc");if(ltb(a)===void 0){if(c==="CAPTIONS_INITIAL_STATE_ON_RECOMMENDED")return d?d==="on":!0;if(c==="CAPTIONS_INITIAL_STATE_OFF_RECOMMENDED")return d==="on"}else return d==="on";return b==="ON"||g.YS(a.videoData,
"yt:cc")==="on"},W4=function(a,b){if(a.B&&(b===void 0||!b)||!a.videoData.captionTracks.length)return!1;
a=a.getAudioTrack();return!!a.j||a.B==="FORCED_ON"},ltb=function(a){var b=void 0,c=g.PB(g.OB(),65);
if(g.MR(a.X)&&c!=null){if(ktb(a)!=null)return!1;b=!c}return b},ntb=function(a){var b;
a.Ob?b=new M4(a.X,a.videoData,a.getAudioTrack(),a.player):a.bb?b=new q4(a.videoData.j,a.player):a.Kb?b=new g.tV(a.X,a.videoData,a.getAudioTrack()):b=new g.xV(a.X,a.videoData.ke,a.videoData.videoId,g.aYa(a.videoData),a.videoData.vn,a.videoData.eventId);return b},Y4=function(a,b){if(a.j){if(a.N&&a.N.D)return a.N.D;
g.jT(a.videoData)&&(b=!0);b||(b=a.Sb?!1:a.Kb?!1:!0);b=b||otb(a);b=g.qV(a.j.B,b);var c=null;if(g.MR(a.X)){var d=a.J.isInline()?void 0:g.GB("yt-player-caption-sticky-language");for(var e=[d,a.videoData.captionsLanguagePreference,a.X.captionsLanguagePreference,g.YS(a.videoData,"yt:cc_default_lang")],f=!1,h=0;h<e.length;h++){var l=e[h];if(l){f=!0;for(var m=0;m<b.length;m++)if(g.eS(b[m])===l)return b[m];for(m=0;m<b.length;m++)if(g.eS(b[m]).split("-")[0]===l.split("-")[0])return b[m]}}if(f&&a.j&&(e=a.j.D,
e.length))for(e=g.v(e),f=e.next();!f.done;f=e.next())if(f=f.value,f.languageCode===d){c=f;break}}else for(d=[a.videoData.captionsLanguagePreference,a.X.captionsLanguagePreference,g.YS(a.videoData,"yt:cc_default_lang")],e=0;e<d.length;e++)for(f=0;f<b.length;f++)if(g.eS(b[f])===d[e])return b[f];d=null;a.N&&a.N.C&&(d=a.N.C);d||(d=b.find(function(n){return n.isDefault})||null);
d||(d=b[0]||X4(a));d&&c&&g.eS(d).split("-")[0]!==c.languageCode.split("-")[0]&&(d=Wrb(d,c));return d}return null},X4=function(a){return a.N&&a.N.j},Z4=function(a){var b=X4(a);
return!!b&&a.B===b},ptb=function(a){var b=Vrb(a.player.getAudioTrack(),g.MR(a.X)),c;
b==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?c=Y4(a,a.Y):b==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"&&W4(a)?c=X4(a):ltb(a)||a.Y||mtb(a)?c=Y4(a,a.Y):W4(a)&&(c=X4(a));if(a.D||a.Fa){var d=g.qV(a.j.B,!0);b=[];for(var e=0;e<d.length;e++){var f=d[e],h=g.yf("TRACK");h.setAttribute("kind","subtitles");h.setAttribute("label",g.cS(f));h.setAttribute("srclang",g.eS(f));h.setAttribute("id",f.toString());a.Fa||h.setAttribute("src",a.j.Pw(f,"vtt"));f===c&&h.setAttribute("default","1");b.push(h)}c=a.J.Je();c.SD(b);c=
c.Ib();a.Jb&&a.Ca.T(c.textTracks,"change",a.wca)}else!a.B&&c&&$4(a,c),a.player.Dc("onCaptionsTrackListChanged"),a.player.Um("onApiChange")},qtb=function(a,b){var c=a.J.Je().Ib().textTracks;
a=a.B.toString();for(var d=0;d<c.length;d++){var e=c[d];e.id===a&&(b?e.mode!=="showing"&&(e.mode="showing"):e.mode==="showing"&&(e.mode="disabled"))}},$4=function(a,b,c){a.loaded&&a.unload();
c!=null&&(a.Y=c,a.Y&&(g.MR(a.X)?a5(a,!!b):b5(a,!!b)));a.B=b;W4(a)&&(a.B=X4(a));var d;rtb(a,(d=a.B)!=null?d:void 0);a.load()},ttb=function(a,b){if(b instanceof C4){var c=a.ra[b.id];
c&&c.B!==b&&(c.dispose(),delete a.ra[b.id],c=null);c||(c=stb(a,b))&&(a.ra[b.id]=c)}else c=b.windowId,a.Va[c]||(a.Va[c]=[]),a.Va[c].push(b)},stb=function(a,b){var c=utb(a);
if(!c)return null;var d=a.B?g.eS(a.B):null;d&&g.fmb.test(d)&&(b.params.Ki=1);var e=a.Eb.getPlayerSize();d=e.height*a.qa.height;e=e.width*a.qa.width;a.X.playerStyle!=="google-live"||a.C.isDefault||Object.assign(b.params,a.C);switch(b.params.jB!=null?b.params.jB:b.j.length>1?1:0){case 1:return new N4(b,a.C,a.G,c.width,c.height,e,d,a.X.experiments,a.WM.bind(a),a.J);case 2:return new S4(b,a.C,a.G,c.width,c.height,e,d,a.X.experiments,a.WM.bind(a),a.J);default:return new r4(b,a.C,a.G,c.width,c.height,e,
d,a.X.experiments,a.WM.bind(a),a.J)}},jtb=function(a,b,c){c=c===void 0?!1:c;
var d=c5.Re;a.C={};Object.assign(a.C,c5);a.C.Re={};Object.assign(a.C.Re,d);a.G={Re:{}};var e=b.backgroundOverride?a.G:a.C,f=b.background||d.background;I4.test(f);e.Re.background=f;e=b.colorOverride?a.G:a.C;f=b.color||d.color;I4.test(f);e.Re.color=f;e=b.windowColorOverride?a.G:a.C;f=b.windowColor||c5.windowColor;I4.test(f);e.windowColor=f;e=b.backgroundOpacityOverride?a.G:a.C;f=b.backgroundOpacity;f==null&&(f=d.backgroundOpacity);e.Re.backgroundOpacity=f;e=b.fontSizeIncrementOverride?a.G:a.C;f=b.fontSizeIncrement;
f==null&&(f=d.fontSizeIncrement);e.Re.fontSizeIncrement=f;f=b.fontStyleOverride?a.G:a.C;e=b.fontStyle;e==null&&(e=d.bold&&d.italic?3:d.bold?1:d.italic?2:0);f=f.Re;switch(e){case 1:f.bold=!0;delete f.italic;break;case 2:delete f.bold;f.italic=!0;break;case 3:f.bold=!0;f.italic=!0;break;default:delete f.bold,delete f.italic}e=b.textOpacityOverride?a.G:a.C;f=b.textOpacity;f==null&&(f=d.textOpacity);e.Re.textOpacity=f;e=b.windowOpacityOverride?a.G:a.C;f=b.windowOpacity;f==null&&(f=c5.windowOpacity);e.windowOpacity=
f;e=b.charEdgeStyleOverride?a.G:a.C;f=b.charEdgeStyle;f==null&&(f=d.charEdgeStyle);e.Re.charEdgeStyle=f;e=b.fontFamilyOverride?a.G:a.C;f=b.fontFamily;f==null&&(f=d.fontFamily);e.Re.fontFamily=f;a.loaded&&a.cU();c&&g.FB("yt-player-caption-display-settings",b,2592E3)},wtb=function(a,b,c){b&&!a.Z?(b=Psb({Ki:0,
lang:"en"}),a.Z=[b,new A4(b.start,b.end-b.start,0,b.id,c!=null?c:"Captions look like this")],a.player.jf(a.Z)):!b&&a.Z&&(vtb(a,a.Z),a.Z=null)},vtb=function(a,b){a.player.Qo(b);
b=g.v(b);for(var c=b.next();!c.done;c=b.next())g.Hb(a.Ha,c.value);o4(a.La)},rtb=function(a,b){a.X.L("html5_modify_caption_vss_logging")&&(a.videoData.vD=b)},utb=function(a){var b=a.Eb.getVideoContentRect(!0).height,c=a.Eb.getVideoContentRect(!0).width;
if(!b||!c)return null;b*=a.qa.height;c*=a.qa.width;return{width:c,height:b}},b5=function(a,b){if(a.storage)try{a.storage.set("module-enabled",b)}catch(c){}},a5=function(a,b){a.J.isInline()||g.FB("yt-player-sticky-caption",b,2592E3)},ktb=function(a){if(!a.J.isInline())return g.GB("yt-player-sticky-caption")},itb=function(a){var b,c=!((b=a.J.Je())==null||!b.xH());
return a.Wa&&c&&!a.bb},otb=function(a){return a.X.L("web_deprecate_always_includes_asr_setting")&&g.MR(a.X)?!0:!!g.PB(g.OB(),66)};
g.ZX.prototype.KE=g.ea(44,function(a){var b=2;this.K.has(a)?b=0:g.E6a(this,a)&&(b=1);return b});
g.A_.prototype.KE=g.ea(43,function(a){return this.Wc.KE(a)});
g.ZX.prototype.IH=g.ea(42,function(a,b,c){this.La.set(a,{Dt:b,qz:c})});
g.A_.prototype.IH=g.ea(41,function(a,b,c){this.Wc.IH(a,b,c)});
g.sV.prototype.sS=g.ea(40,function(){return!1});
g.sV.prototype.yu=g.ea(39,function(){});
g.tV.prototype.yu=g.ea(38,function(a,b,c){var d=this;this.Ma();b=this.Pw(a,b);this.Ls();this.j=g.PA(b,{format:"RAW",onSuccess:function(e){d.j=null;c(e.responseText,a)},
withCredentials:!0})});
g.xV.prototype.yu=g.ea(37,function(a,b,c){var d=this;this.Ma();b=this.Pw(a,b);this.Ls();this.j=g.PA(b,{format:"RAW",onSuccess:function(e){d.j=null;c(e.responseText,a)},
withCredentials:!0})});
g.WU.prototype.Ez=g.ea(36,function(){for(var a=g.of(document,"track",void 0,this.j),b=0;b<a.length;b++)g.Hf(a[b])});
g.DX.prototype.Ez=g.ea(35,function(){this.mediaElement.Ez()});
g.WU.prototype.yH=g.ea(34,function(){return!(!this.j.textTracks||!this.j.textTracks.addEventListener)});
g.DX.prototype.yH=g.ea(33,function(){return this.mediaElement.yH()});
g.WU.prototype.xH=g.ea(32,function(){return!!this.j.textTracks});
g.DX.prototype.xH=g.ea(31,function(){return this.mediaElement.xH()});
g.WU.prototype.SD=g.ea(30,function(a){for(var b=0;b<a.length;b++)this.j.appendChild(a[b])});
g.DX.prototype.SD=g.ea(29,function(a){this.mediaElement.SD(a)});
g.v_.prototype.cF=g.ea(19,function(){return this.N});
g.G0.prototype.cF=g.ea(18,function(){var a;return((a=g.DT(this))==null?void 0:a.jA())||null});
g.JT.prototype.jA=g.ea(17,function(){return this.app.cF()});
g.v0.prototype.jA=g.ea(16,function(){var a;return((a=this.ya)==null?void 0:a.cF())||null});
g.uP.prototype.MJ=g.ea(2,function(a){return(a=this.Mn(a))?a.j:0});
g.oTa.prototype.MJ=g.ea(1,function(){return 0});
var $rb=/#(.)(.)(.)/,Zrb=/^#(?:[0-9a-f]{3}){1,2}$/i,gsb={aa:"Afar",ab:"Abkhazian",ace:"Acehnese",ach:"Acoli",ada:"Adangme",ady:"Adyghe",ae:"Avestan",aeb:"Tunisian Arabic",af:"Afrikaans",afh:"Afrihili",agq:"Aghem",ain:"Ainu",ak:"Akan",akk:"Akkadian",akz:"Alabama",ale:"Aleut",aln:"Gheg Albanian",alt:"Southern Altai",am:"Amharic",an:"Aragonese",ang:"Old English",anp:"Angika",ar:"Arabic",ar_001:"Arabic (world)",arc:"Aramaic",arn:"Mapuche",aro:"Araona",arp:"Arapaho",arq:"Algerian Arabic",ars:"Najdi Arabic",
arw:"Arawak",ary:"Moroccan Arabic",arz:"Egyptian Arabic",as:"Assamese",asa:"Asu",ase:"American Sign Language",ast:"Asturian",av:"Avaric",avk:"Kotava",awa:"Awadhi",ay:"Aymara",az:"Azerbaijani",az_Cyrl:"Azerbaijani (Cyrillic)",az_Latn:"Azerbaijani (Latin)",ba:"Bashkir",bal:"Baluchi",ban:"Balinese",bar:"Bavarian",bas:"Basaa",bax:"Bamun",bbc:"Batak Toba",bbj:"Ghomala",be:"Belarusian",bej:"Beja",bem:"Bemba",bew:"Betawi",bez:"Bena",bfd:"Bafut",bfq:"Badaga",bg:"Bulgarian",bgc:"Haryanvi",bgn:"Western Balochi",
bho:"Bhojpuri",bi:"Bislama",bik:"Bikol",bin:"Bini",bjn:"Banjar",bkm:"Kom",bla:"Siksik\u00e1",blo:"Anii",bm:"Bambara",bn:"Bangla",bo:"Tibetan",bpy:"Bishnupriya",bqi:"Bakhtiari",br:"Breton",bra:"Braj",brh:"Brahui",brx:"Bodo",bs:"Bosnian",bs_Cyrl:"Bosnian (Cyrillic)",bs_Latn:"Bosnian (Latin)",bss:"Akoose",bua:"Buriat",bug:"Buginese",bum:"Bulu",byn:"Blin",byv:"Medumba",ca:"Catalan",cad:"Caddo",car:"Carib",cay:"Cayuga",cch:"Atsam",ccp:"Chakma",ce:"Chechen",ceb:"Cebuano",cgg:"Chiga",ch:"Chamorro",chb:"Chibcha",
chg:"Chagatai",chk:"Chuukese",chm:"Mari",chn:"Chinook Jargon",cho:"Choctaw",chp:"Chipewyan",chr:"Cherokee",chy:"Cheyenne",ckb:"Central Kurdish",co:"Corsican",cop:"Coptic",cps:"Capiznon",cr:"Cree",crh:"Crimean Tatar",cs:"Czech",csb:"Kashubian",csw:"Swampy Cree",cu:"Church Slavic",cv:"Chuvash",cy:"Welsh",da:"Danish",dak:"Dakota",dar:"Dargwa",dav:"Taita",de:"German",de_AT:"German (Austria)",de_CH:"German (Switzerland)",del:"Delaware",den:"Slave",dgr:"Dogrib",din:"Dinka",dje:"Zarma",doi:"Dogri",dsb:"Lower Sorbian",
dua:"Duala",dum:"Middle Dutch",dv:"Divehi",dyo:"Jola-Fonyi",dyu:"Dyula",dz:"Dzongkha",dzg:"Dazaga",ebu:"Embu",ee:"Ewe",efi:"Efik",egy:"Ancient Egyptian",eka:"Ekajuk",el:"Greek",elx:"Elamite",en:"English",en_AU:"English (Australia)",en_CA:"English (Canada)",en_GB:"English (United Kingdom)",en_US:"English (United States)",enm:"Middle English",eo:"Esperanto",es:"Spanish",es_419:"Spanish (Latin America)",es_ES:"Spanish (Spain)",es_MX:"Spanish (Mexico)",et:"Estonian",eu:"Basque",ewo:"Ewondo",fa:"Persian",
fa_AF:"Persian (Afghanistan)",fan:"Fang",fat:"Fanti",ff:"Fula",ff_Adlm:"Fula (Adlam)",ff_Latn:"Fula (Latin)",fi:"Finnish",fil:"Filipino",fj:"Fijian",fo:"Faroese",fon:"Fon",fr:"French",fr_CA:"French (Canada)",fr_CH:"French (Switzerland)",frm:"Middle French",fro:"Old French",frr:"Northern Frisian",frs:"Eastern Frisian",fur:"Friulian",fy:"Western Frisian",ga:"Irish",gaa:"Ga",gay:"Gayo",gba:"Gbaya",gd:"Scottish Gaelic",gez:"Geez",gil:"Gilbertese",gl:"Galician",gmh:"Middle High German",gn:"Guarani",goh:"Old High German",
gon:"Gondi",gor:"Gorontalo",got:"Gothic",grb:"Grebo",grc:"Ancient Greek",gsw:"Swiss German",gu:"Gujarati",guz:"Gusii",gv:"Manx",gwi:"Gwich\u02bcin",ha:"Hausa",hai:"Haida",haw:"Hawaiian",he:"Hebrew",hi:"Hindi",hi_Latn:"Hindi (Latin)",hil:"Hiligaynon",hit:"Hittite",hmn:"Hmong",ho:"Hiri Motu",hr:"Croatian",hsb:"Upper Sorbian",ht:"Haitian Creole",hu:"Hungarian",hup:"Hupa",hy:"Armenian",hz:"Herero",ia:"Interlingua",iba:"Iban",ibb:"Ibibio",id:"Indonesian",ie:"Interlingue",ig:"Igbo",ii:"Sichuan Yi",ik:"Inupiaq",
ilo:"Iloko","in":"Indonesian",inh:"Ingush",io:"Ido",is:"Icelandic",it:"Italian",iu:"Inuktitut",iw:"Hebrew",ja:"Japanese",jbo:"Lojban",jgo:"Ngomba",jmc:"Machame",jpr:"Judeo-Persian",jrb:"Judeo-Arabic",jv:"Javanese",ka:"Georgian",kaa:"Kara-Kalpak",kab:"Kabyle",kac:"Kachin",kaj:"Jju",kam:"Kamba",kaw:"Kawi",kbd:"Kabardian",kbl:"Kanembu",kcg:"Tyap",kde:"Makonde",kea:"Kabuverdianu",kfo:"Koro",kg:"Kongo",kgp:"Kaingang",kha:"Khasi",kho:"Khotanese",khq:"Koyra Chiini",ki:"Kikuyu",kj:"Kuanyama",kk:"Kazakh",
kkj:"Kako",kl:"Kalaallisut",kln:"Kalenjin",km:"Khmer",kmb:"Kimbundu",kn:"Kannada",ko:"Korean",kok:"Konkani",kos:"Kosraean",kpe:"Kpelle",kr:"Kanuri",krc:"Karachay-Balkar",krl:"Karelian",kru:"Kurukh",ks:"Kashmiri",ks_Arab:"Kashmiri (Arabic)",ks_Deva:"Kashmiri (Devanagari)",ksb:"Shambala",ksf:"Bafia",ksh:"Colognian",ku:"Kurdish",kum:"Kumyk",kut:"Kutenai",kv:"Komi",kw:"Cornish",kxv:"Kuvi",kxv_Deva:"Kuvi (Devanagari)",kxv_Latn:"Kuvi (Latin)",kxv_Orya:"Kuvi (Odia)",kxv_Telu:"Kuvi (Telugu)",ky:"Kyrgyz",
la:"Latin",lad:"Ladino",lag:"Langi",lah:"Western Panjabi",lam:"Lamba",lb:"Luxembourgish",lez:"Lezghian",lg:"Ganda",li:"Limburgish",lij:"Ligurian",lkt:"Lakota",lmo:"Lombard",ln:"Lingala",lo:"Lao",lol:"Mongo",loz:"Lozi",lrc:"Northern Luri",lt:"Lithuanian",lu:"Luba-Katanga",lua:"Luba-Lulua",lui:"Luiseno",lun:"Lunda",luo:"Luo",lus:"Mizo",luy:"Luyia",lv:"Latvian",mad:"Madurese",maf:"Mafa",mag:"Magahi",mai:"Maithili",mak:"Makasar",man:"Mandingo",mas:"Masai",mde:"Maba",mdf:"Moksha",mdr:"Mandar",men:"Mende",
mer:"Meru",mfe:"Morisyen",mg:"Malagasy",mga:"Middle Irish",mgh:"Makhuwa-Meetto",mgo:"Meta\u02bc",mh:"Marshallese",mi:"M\u0101ori",mic:"Mi'kmaw",min:"Minangkabau",mk:"Macedonian",ml:"Malayalam",mn:"Mongolian",mnc:"Manchu",mni:"Manipuri",mni_Beng:"Manipuri (Bangla)",mo:"Romanian",moh:"Mohawk",mos:"Mossi",mr:"Marathi",ms:"Malay",mt:"Maltese",mua:"Mundang",mul:"Multiple languages",mus:"Muscogee",mwl:"Mirandese",mwr:"Marwari",my:"Burmese",mye:"Myene",myv:"Erzya",mzn:"Mazanderani",na:"Nauru",nap:"Neapolitan",
naq:"Nama",nb:"Norwegian Bokm\u00e5l",nd:"North Ndebele",nds:"Low German",nds_NL:"Low German (Netherlands)",ne:"Nepali","new":"Newari",ng:"Ndonga",nia:"Nias",niu:"Niuean",nl:"Dutch",nl_BE:"Dutch (Belgium)",nmg:"Kwasio",nn:"Norwegian Nynorsk",nnh:"Ngiemboon",no:"Norwegian",nog:"Nogai",non:"Old Norse",nqo:"N\u2019Ko",nr:"South Ndebele",nso:"Northern Sotho",nus:"Nuer",nv:"Navajo",nwc:"Classical Newari",ny:"Nyanja",nym:"Nyamwezi",nyn:"Nyankole",nyo:"Nyoro",nzi:"Nzima",oc:"Occitan",oj:"Ojibwa",om:"Oromo",
or:"Odia",os:"Ossetic",osa:"Osage",ota:"Ottoman Turkish",pa:"Punjabi",pa_Arab:"Punjabi (Arabic)",pa_Guru:"Punjabi (Gurmukhi)",pag:"Pangasinan",pal:"Pahlavi",pam:"Pampanga",pap:"Papiamento",pau:"Palauan",pcm:"Nigerian Pidgin",peo:"Old Persian",phn:"Phoenician",pi:"Pali",pl:"Polish",pon:"Pohnpeian",prg:"Prussian",pro:"Old Proven\u00e7al",ps:"Pashto",pt:"Portuguese",pt_BR:"Portuguese (Brazil)",pt_PT:"Portuguese (Portugal)",qu:"Quechua",raj:"Rajasthani",rap:"Rapanui",rar:"Rarotongan",rm:"Romansh",rn:"Rundi",
ro:"Romanian",ro_MD:"Romanian (Moldova)",rof:"Rombo",rom:"Romany",ru:"Russian",rup:"Aromanian",rw:"Kinyarwanda",rwk:"Rwa",sa:"Sanskrit",sad:"Sandawe",sah:"Yakut",sam:"Samaritan Aramaic",saq:"Samburu",sas:"Sasak",sat:"Santali",sat_Olck:"Santali (Ol Chiki)",sba:"Ngambay",sbp:"Sangu",sc:"Sardinian",scn:"Sicilian",sco:"Scots",sd:"Sindhi",sd_Arab:"Sindhi (Arabic)",sd_Deva:"Sindhi (Devanagari)",se:"Northern Sami",see:"Seneca",seh:"Sena",sel:"Selkup",ses:"Koyraboro Senni",sg:"Sango",sga:"Old Irish",sh:"Serbo-Croatian",
shi:"Tachelhit",shi_Latn:"Tachelhit (Latin)",shi_Tfng:"Tachelhit (Tifinagh)",shn:"Shan",shu:"Chadian Arabic",si:"Sinhala",sid:"Sidamo",sk:"Slovak",sl:"Slovenian",sm:"Samoan",sma:"Southern Sami",smj:"Lule Sami",smn:"Inari Sami",sms:"Skolt Sami",sn:"Shona",snk:"Soninke",so:"Somali",sog:"Sogdien",sq:"Albanian",sr:"Serbian",sr_Cyrl:"Serbian (Cyrillic)",sr_Latn:"Serbian (Latin)",srn:"Sranan Tongo",srr:"Serer",ss:"Swati",ssy:"Saho",st:"Southern Sotho",su:"Sundanese",su_Latn:"Sundanese (Latin)",suk:"Sukuma",
sus:"Susu",sux:"Sumerian",sv:"Swedish",sw:"Swahili",sw_CD:"Swahili (Congo - Kinshasa)",swb:"Comorian",syc:"Classical Syriac",syr:"Syriac",szl:"Silesian",ta:"Tamil",te:"Telugu",tem:"Timne",teo:"Teso",ter:"Tereno",tet:"Tetum",tg:"Tajik",th:"Thai",ti:"Tigrinya",tig:"Tigre",tiv:"Tiv",tk:"Turkmen",tkl:"Tokelau",tl:"Tagalog",tlh:"Klingon",tli:"Tlingit",tmh:"Tamashek",tn:"Tswana",to:"Tongan",tog:"Nyasa Tonga",tok:"Toki Pona",tpi:"Tok Pisin",tr:"Turkish",trv:"Taroko",ts:"Tsonga",tsi:"Tsimshian",tt:"Tatar",
tum:"Tumbuka",tvl:"Tuvalu",tw:"Twi",twq:"Tasawaq",ty:"Tahitian",tyv:"Tuvinian",tzm:"Central Atlas Tamazight",udm:"Udmurt",ug:"Uyghur",uga:"Ugaritic",uk:"Ukrainian",umb:"Umbundu",ur:"Urdu",uz:"Uzbek",uz_Arab:"Uzbek (Arabic)",uz_Cyrl:"Uzbek (Cyrillic)",uz_Latn:"Uzbek (Latin)",vai:"Vai",vai_Latn:"Vai (Latin)",vai_Vaii:"Vai (Vai)",ve:"Venda",vec:"Venetian",vi:"Vietnamese",vmw:"Makhuwa",vo:"Volap\u00fck",vot:"Votic",vun:"Vunjo",wa:"Walloon",wae:"Walser",wal:"Wolaytta",war:"Waray",was:"Washo",wo:"Wolof",
xal:"Kalmyk",xh:"Xhosa",xnr:"Kangri",xog:"Soga",yao:"Yao",yap:"Yapese",yav:"Yangben",ybb:"Yemba",yi:"Yiddish",yo:"Yoruba",yrl:"Nheengatu",yue:"Cantonese",yue_Hans:"Cantonese (Simplified)",yue_Hant:"Cantonese (Traditional)",za:"Zhuang",zap:"Zapotec",zbl:"Blissymbols",zen:"Zenaga",zgh:"Standard Moroccan Tamazight",zh:"Chinese",zh_Hans:"Chinese (Simplified)",zh_Hant:"Chinese (Traditional)",zh_TW:"Chinese (Taiwan)",zu:"Zulu",zun:"Zuni",zxx:"No linguistic content",zza:"Zaza"};
p4.prototype.contains=function(a){a=g.Sb(this.segments,a);return a>=0||a<0&&(-a-1)%2===1};
p4.prototype.length=function(){return this.segments.length/2};
g.y(dsb,g.I);g.k=dsb.prototype;g.k.xa=function(){g.I.prototype.xa.call(this);this.C&&this.C.cancel()};
g.k.wB=function(){this.seekTo(this.player.getCurrentTime())};
g.k.seekTo=function(a){a-=this.player.Mc();var b=this.j;this.j=g.Bb(this.qa.Er(a).jb);b!==this.j&&this.Y&&this.Y()};
g.k.reset=function(){this.D=new p4;this.K=-1;this.C&&(this.C.cancel(),this.C=null)};
g.k.PZ=function(){this.Ma();var a;if(a=this.j!=null)a=this.j,a=a.j.Ts(a);if(a&&!this.C&&!(this.j&&this.j.startTime-this.player.getCurrentTime()>30)){a=this.j;a=a.j.qD(a);var b=a.jb[0],c;if((c=this.player.getVideoData())==null?0:c.enableServerStitchedDai)if(c=this.player.jA()){var d=b.j.info.id,e=b.Pa,f=a.jb[0].C;if(this.policy.Ha){if(c=c.PJ(f,e,d,3))a.D=c}else if(d=c.cA(f,e,d,3))if(c=c.KE(e),c===0)d&&(a.j=new g.nP(d));else if(c===2){this.N.start();esb(this)&&this.seekTo(this.player.getCurrentTime());
return}}b.j.index.Yn(b.Pa)?(this.D.contains(a.jb[0].Pa)||fsb(this,a),this.j=g.Bb(a.jb)):esb(this)&&this.seekTo(this.player.getCurrentTime())}this.N.start()};
g.y(q4,g.sV);g.k=q4.prototype;g.k.yu=function(a,b,c){var d=this;this.Ls();b=isb(this,a.getId());b||(b=a.languageCode,b=this.j.isManifestless?jsb(this,b,"386"):jsb(this,b));if(b){var e=(b.index.MJ(b.index.Pn())-b.index.getStartTime(b.index.Pn()))*1E3,f=new g.d0a(this.X),h=function(){d.C&&d.C.reset();d.G=!0};
this.X.L("html5_keep_caption_data_after_seek")&&(h=null);this.C=new dsb(f,this.J,b,function(l,m){c(l,a,m,e)},this.K||g.cK(b.info),h)}};
g.k.sS=function(){var a=this.G;this.G=!1;return a};
g.k.WA=function(a){var b=this.K?[new g.bS({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.bS({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]:this.j.isManifestless?hsb(this,"386"):hsb(this);b=g.v(b);for(var c=b.next();!c.done;c=b.next())g.rV(this.B,c.value);a()};
g.k.Ls=function(){this.C&&(this.C.dispose(),this.C=null)};
g.k.Pw=function(){return""};
var I4=/^#(?:[0-9a-f]{3}){1,2}$/i;var nsb=["left","right","center","justify"];g.y(r4,g.W);g.k=r4.prototype;g.k.S4=function(a,b){this.bb=a;this.fb=b;var c=g.Xs(this.element,this.element.parentElement);this.rb=a-c.x;this.Eb=b-c.y};
g.k.R4=function(a,b){if(a!==this.bb||b!==this.fb){g.Rv(this.element,"ytp-dragging")||g.Sv(this.element,"ytp-dragging");var c=g.Zs(this.element);a=a-this.rb-.02*this.playerWidth;var d=b-this.Eb-.02*this.playerHeight,e=(a+c.width/2)/this.maxWidth*3;e=Math.floor(g.ze(e,0,2));var f=(d+c.height/2)/this.maxHeight*3;f=Math.floor(g.ze(f,0,2));b=e+f*3;a=(a+e/2*c.width)/this.maxWidth;a=g.ze(a,0,1)*100;c=(d+f/2*c.height)/this.maxHeight;c=g.ze(c,0,1)*100;this.B.params.mm=b;this.B.params.Uo=c;this.B.params.pk=
a;this.B.params.isDefault=!1;this.j.mm=b;this.j.Uo=c;this.j.pk=a;this.j.isDefault=!1;this.ra.mm=b;this.ra.Uo=c;this.ra.pk=a;this.ra.isDefault=!1;this.e1()}};
g.k.Q4=function(){g.Uv(this.element,"ytp-dragging")};
g.k.e1=function(){this.kC(this.K)};
g.k.getType=function(){return this.type};
g.k.kC=function(a){var b=this.Gb?0:Math.min(this.hY(),this.maxWidth),c=this.gY(),d=this.Gb;if(d){var e=getComputedStyle(this.D.parentNode);e=s4(e.borderLeftWidth)+s4(e.borderRightWidth)+s4(e.paddingLeft)+s4(e.paddingRight)}else e=0;var f=e;e="";this.B.params.Ki===3&&(e="rotate(180deg)");var h=d?"calc(96% - "+f+"px)":"96%";g.Ns(this.element,{top:0,left:0,right:"",bottom:"",width:b?b+"px":"",height:c?c+"px":"","max-width":h,"max-height":h,margin:"",transform:""});this.UN(a);e={transform:e,top:"",left:"",
width:b?b+"px":"",height:c?c+"px":"","max-width":"","max-height":""};var l=this.j.pk*.96+2;h=this.j.mm;switch(h){case 0:case 3:case 6:(d=this.j.Re.fontSizeIncrement)&&d>0&&this.j.Ki!==2&&this.j.Ki!==3&&(l=Math.max(l/(1+d*2),2));e.left=l+"%";break;case 1:case 4:case 7:e.left=l+"%";l=this.D.offsetWidth;b||l?(b=b||l+1,e.width=b+"px",e["margin-left"]=d?b/-2-f/2+"px":b/-2+"px"):e.transform+=" translateX(-50%)";break;case 2:case 5:case 8:e.right=100-l+"%"}d=this.j.Uo*.96+2;switch(h){case 0:case 1:case 2:e.top=
d+"%";break;case 3:case 4:case 5:e.top=d+"%";(c=c||this.element.clientHeight)?(e.height=c+"px",e["margin-top"]=c/-2+"px"):e.transform+=" translateY(-50%)";break;case 6:case 7:case 8:e.bottom=100-d+"%"}g.Ns(this.element,e);if(this.G){c=this.D.offsetHeight;d=1;for(b=0;b<a.length;b++)e=a[b],typeof e.text==="string"&&(d+=e.text.split("\n").length-1,e.append||b===0||d++);c/=d;this.G.style.height=c+"px";this.G.style.width=c+"px";this.element.style.paddingLeft=c+5+"px";this.element.style.paddingRight=c+
5+"px";a=Number(this.element.style.marginLeft.replace("px",""))-c-5;c=Number(this.element.style.marginRight.replace("px",""))-c-5;this.element.style.marginLeft=a+"px";this.element.style.marginRight=c+"px"}};
g.k.UN=function(a){var b;for(b=0;b<a.length&&a[b]===this.K[b];b++);if(this.Ha||this.K.length>b)b=0,this.Ha=!1,this.K=[],this.N=this.Na=this.La=null,g.Cf(this.D);for(;b<a.length;b++)ssb(this,a[b])};
g.k.hY=function(){return 0};
g.k.gY=function(){return 0};
g.k.toString=function(){return g.W.prototype.toString.call(this)};usb.prototype.clear=function(){this.C=this.time=this.mode=0;this.j=[];this.reset()};
usb.prototype.reset=function(){this.mode=0;this.D.reset(0);this.G.reset(1)};
var vsb=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];t4.prototype.set=function(a){this.type=a};
t4.prototype.get=function(){return this.type};
u4.prototype.clear=function(){this.state=0};
u4.prototype.update=function(){this.state=this.state===2?1:0};
u4.prototype.qe=function(){return this.state!==0};
u4.prototype.matches=function(a,b){return this.qe()&&a===this.jw&&b===this.Zs};
Asb.prototype.reset=function(){this.timestamp=this.j=0};
v4.prototype.updateTime=function(a){for(var b=1;b<=15;++b)for(var c=1;c<=32;++c)this.B[b][c].timestamp=a};
v4.prototype.debugString=function(){for(var a="\n",b=1;b<=15;++b){for(var c=1;c<=32;++c){var d=this.B[b][c];a=d.j===0?a+"_":a+String.fromCharCode(d.j)}a+="\n"}return a};
v4.prototype.reset=function(a){for(var b=0;b<=15;b++)for(var c=0;c<=32;c++)this.B[b][c].reset();this.C=a;this.j=0;this.col=this.row=1};
var Bsb=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],Csb=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],Dsb=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],Esb=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];Isb.prototype.reset=function(a,b){this.G=b;this.style.set(2);this.B=this.K;this.D=this.N;this.j=this.B;var c=(a<<2)+(b<<1);this.K.reset(c);this.N.reset(c);this.text.reset((a<<2)+(b<<1)+1)};
tsb.prototype.reset=function(a){this.G=a;this.B.clear();this.D=this.C;this.C.reset(a,0);this.K.reset(a,1)};Msb.prototype.D=function(){};g.y(A4,g.XI);A4.prototype.toString=function(){return g.XI.prototype.toString.call(this)};g.y(B4,g.I);B4.prototype.Io=function(){return[]};
B4.prototype.reset=function(){};g.y(C4,g.XI);C4.prototype.toString=function(){return g.XI.prototype.toString.call(this)};
var D4=0;g.y(E4,B4);E4.prototype.reset=function(){this.K={};this.B=this.j=null;this.G=!0};
E4.prototype.Io=function(a,b){a=a.firstChild;a.getAttribute("format");b=b||0;Number.isFinite(b);a=Array.from(a.childNodes);a=g.v(a);for(var c=a.next();!c.done;c=a.next())if(c=c.value,c.nodeType===1)switch(c.tagName){case "head":var d=c;break;case "body":var e=c}if(d)for(d=Array.from(d.childNodes),d=g.v(d),a=d.next();!a.done;a=d.next())if(a=a.value,a.nodeType===1)switch(a.tagName){case "pen":c=a.getAttribute("id");var f=this.pens,h={},l=a.getAttribute("p");l&&Object.assign(h,this.pens[l]);l=G4(a,"b");
l!=null&&(h.bold=l);l=G4(a,"i");l!=null&&(h.italic=l);l=G4(a,"u");l!=null&&(h.underline=l);l=H4(a,"et");l!=null&&(h.charEdgeStyle=l);l=H4(a,"of");l!=null&&(h.offset=l);l=J4(a,"bc");l!=null&&(h.background=l);l=J4(a,"ec");l!=null&&(h.pO=l);l=J4(a,"fc");l!=null&&(h.color=l);l=H4(a,"fs");l!=null&&l!==0&&(h.fontFamily=l);l=F4(a,"sz");l!==void 0&&(h.fontSizeIncrement=l/100-1);l=F4(a,"bo");l!==void 0&&(h.backgroundOpacity=l/255);l=F4(a,"fo");l!==void 0&&(h.textOpacity=l/255);l=H4(a,"rb");l!=null&&l!==10&&
l!==0&&(h.eg=l>10?l-1:l);a=H4(a,"hg");a!=null&&(h.aZ=a);f[c]=h;break;case "ws":c=a.getAttribute("id");this.Z[c]=Qsb(this,a);break;case "wp":c=a.getAttribute("id"),this.N[c]=Rsb(this,a)}if(e){d=[];e=Array.from(e.childNodes);e=g.v(e);for(a=e.next();!a.done;a=e.next())if(a=a.value,a.nodeType===1)switch(a.tagName){case "w":this.j=Ssb(this,a,b,!1);(a=this.K[this.j.id])&&a.end>this.j.start&&(a.end=this.j.start);this.K[this.j.id]=this.j;d.push(this.j);break;case "p":var m=a;l=b;c=[];f=m.getAttribute("w")||
this.D;h=!!G4(m,"a");l=(F4(m,"t")||0)+l;var n=F4(m,"d")||5E3;h||(!this.G&&this.B&&this.B.windowId===f&&this.B.end>l&&(this.B.end=l),this.B&&this.B.text==="\n"&&(this.B.text=""));var p=h?6:5,q=m.getAttribute("p");q=q?this.pens[q]:null;var r=Array.from(m.childNodes);r.length&&(this.G=m.getAttribute("d")!=null);for(m=0;m<r.length;m++){var t=r[m],u=void 0;m>0&&(h=!0);var w=void 0;t.nodeType===1&&(w=t);if(w&&w.tagName==="s"){if((t=(t=w.getAttribute("p"))?this.pens[t]:null)&&t.eg&&(t.eg===1?(t=r.slice(m,
m+4),t.length===4&&(u=Osb(l,n,f,h,p,t,this.pens),m+=3)):u=Osb(l,n,f,h,p,[w],this.pens)),!u){var A=w;u=l;w=n;t=f;var C=h,F=p,H=A.textContent?A.textContent:"",L=A.getAttribute("p");L=L?this.pens[L]:null;A=F4(A,"t")||0;u=new A4(u+A,w-A,F,t,H,C,L)}}else u=new A4(l,n,p,f,t.textContent||"",h,q);c.push(u);this.B=u}if(c.length>0)for(c[0].windowId===this.D&&(this.j=Ssb(this,a,b,!0),d.push(this.j)),a=g.v(c),c=a.next();!c.done;c=a.next())c=c.value,c.windowId=this.j.id,this.j.j.push(c),d.push(c)}b=d}else b=[];
return b};var xtb=new Map([[9,1],[10,1],[11,2],[12,3],[13,4],[14,5]]);g.y(K4,B4);K4.prototype.reset=function(){this.B.clear()};
K4.prototype.Io=function(a,b){var c=JSON.parse(a);if(!c)return[];if(c.pens){a=0;for(var d=g.v(c.pens),e=d.next();!e.done;e=d.next()){e=e.value;var f={},h=e.pParentId;h&&Object.assign(f,this.j.get(h));e.bAttr&&(f.bold=!0);e.iAttr&&(f.italic=!0);e.uAttr&&(f.underline=!0);h=e.ofOffset;h!=null&&(f.offset=h);e.szPenSize!==void 0&&(f.fontSizeIncrement=e.szPenSize/100-1);h=e.etEdgeType;h!=null&&(f.charEdgeStyle=h);e.ecEdgeColor!==void 0&&(f.pO=L4(e.ecEdgeColor));h=e.fsFontStyle;h!=null&&h!==0&&(f.fontFamily=
h);e.fcForeColor!==void 0&&(f.color=L4(e.fcForeColor));e.foForeAlpha!==void 0&&(f.textOpacity=e.foForeAlpha/255);e.bcBackColor!==void 0&&(f.background=L4(e.bcBackColor));e.boBackAlpha!==void 0&&(f.backgroundOpacity=e.boBackAlpha/255);(h=e.rbRuby)&&h!==10&&(f.eg=h>10?h-1:h,f.So=xtb.get(f.eg));e.hgHorizGroup&&(f.aZ=e.hgHorizGroup);this.j.set(a++,f)}}if(c.wsWinStyles)for(a=0,d=g.v(c.wsWinStyles),e=d.next();!e.done;e=d.next())e=e.value,f={},(h=e.wsParentId)?Object.assign(f,this.D.get(h)):Object.assign(f,
this.G),e.mhModeHint!==void 0&&(f.jB=e.mhModeHint),e.juJustifCode!==void 0&&(f.textAlign=e.juJustifCode),e.pdPrintDir!==void 0&&(f.Ki=e.pdPrintDir),e.sdScrollDir!==void 0&&(f.JT=e.sdScrollDir),e.wfcWinFillColor!==void 0&&(f.windowColor=L4(e.wfcWinFillColor)),e.wfoWinFillAlpha!==void 0&&(f.windowOpacity=e.wfoWinFillAlpha/255),this.D.set(a++,f);if(c.wpWinPositions)for(a=0,d=g.v(c.wpWinPositions),e=d.next();!e.done;e=d.next())e=e.value,f={},(h=e.wpParentId)&&Object.assign(f,this.C.get(h)),e.ahHorPos!==
void 0&&(f.pk=e.ahHorPos),e.apPoint!==void 0&&(f.mm=e.apPoint),e.avVerPos!==void 0&&(f.Uo=e.avVerPos),e.ccCols!==void 0&&(f.ut=e.ccCols),e.rcRows!==void 0&&(f.ws=e.rcRows),this.C.set(a++,f);if(c.events){a=[];c=g.v(c.events);for(d=c.next();!d.done;d=c.next()){var l=d.value;e=(l.tStartMs||0)+b;f=l.dDurationMs||0;if(l.id)h=String(l.id),d=Tsb(this,l,e,f,h),a.push(d),this.B.set(h,d);else{l.wWinId?h=l.wWinId.toString():(h="_"+D4++,d=Tsb(this,l,e,f,h),a.push(d),this.B.set(h,d));d=a;var m=l;f===0&&(f=5E3);
l=this.B.get(h);var n=!!m.aAppend,p=n?6:5,q=m.segs,r=null;m.pPenId&&(r=this.j.get(m.pPenId));for(m=0;m<q.length;m++){var t=q[m],u=t.utf8;if(u){var w=t.tOffsetMs||0,A=null;t.pPenId&&(A=this.j.get(t.pPenId));if((l.params.jB!=null?l.params.jB:l.j.length>1?1:0)===2&&n&&u==="\n")continue;t=null;var C=[],F;if(F=A&&A.eg===1){F=q;var H=m;if(H+3>=F.length||!F[H+1].pPenId||!F[H+2].pPenId||!F[H+3].pPenId)F=!1;else{var L=F[H+1].pPenId;(L=this.j.get(L))&&L.eg&&L.eg===2?(L=F[H+2].pPenId,L=this.j.get(L),!L||!L.eg||
L.eg<3?F=!1:(L=F[H+3].pPenId,F=(L=this.j.get(L))&&L.eg&&L.eg===2?!0:!1)):F=!1}}if(F)w=q[m+1].utf8,t=q[m+3].utf8,F=q[m+2].utf8,H=this.j.get(q[m+2].pPenId),u=Nsb(u,w,F,t,H),t=new A4(e,f,p,h,u,n,A),m+=3;else{if(u.indexOf("<")>-1){var N=void 0;C=A;F=r;H=e;L=f;var P=w,fa=p,ma=n,pa=[],ia=g.e2("<html>"+u+"</html>");if(!ia.getElementsByTagName("parsererror").length&&((N=ia.firstChild)==null?0:N.childNodes.length))for(N=g.v(ia.firstChild.childNodes),ia=N.next();!ia.done;ia=N.next()){ia=ia.value;var ta=void 0,
aa=void 0,T=(aa=(ta=ia.textContent)==null?void 0:ta.replace(/\n/g,""))!=null?aa:"";if(ia.nodeType!==3||T&&T.match(/^ *$/)==null){ta={};Object.assign(ta,C||F);aa=void 0;switch((aa=ia)==null?void 0:aa.tagName){case "b":ta.bold=!0;break;case "i":ta.italic=!0;break;case "u":ta.underline=!0}pa.push(new A4(H+P,L-P,fa,l.id,T,ma,ta))}}C=pa}C.length||(C=[new A4(e+w,f-w,p,l.id,u,n,A||r)])}if(C.length)for(n=g.v(C),A=n.next();!A.done;A=n.next())A=A.value,d.push(A),l.j.push(A);else t&&(d.push(t),l.j.push(t))}n=
!0}}}b=a}else b=[];return b};g.y(M4,g.sV);M4.prototype.yu=function(a,b,c){Yrb(this.videoData.videoId,a.vssId,c)};
M4.prototype.WA=function(a){if(this.audioTrack)for(var b=g.v(this.audioTrack.captionTracks),c=b.next();!c.done;c=b.next())g.rV(this.B,c.value);a()};g.y(N4,r4);N4.prototype.UN=function(a){var b=this.B.j;r4.prototype.UN.call(this,a);for(a=a.length;a<b.length;a++){var c=b[a];if(f&&c.j===e)var d=f;else{d={};Object.assign(d,c.j);Object.assign(d,ytb);var e=c.j;var f=d}ssb(this,c,d)}};
var ytb={P9:!0};g.y(O4,Msb);O4.prototype.D=function(a,b,c,d,e){if(c<d){var f="_"+D4++;c=c/1E3-this.K;d=d/1E3-this.K;a=new C4(c,d-c,5,f,{textAlign:0,mm:0,pk:b*2.5,Uo:a*5.33});e=new A4(c,d-c,5,f,e);this.B.push(a);this.B.push(e)}};
g.y(R4,B4);R4.prototype.Io=function(a){a=new O4(a,a.byteLength,this.B);if(Usb(a)){for(;a.byteOffset<a.j.byteLength;)for(a.version===0?a.C=Q4(a)*(1E3/45):a.version===1&&(a.C=Q4(a)*4294967296+Q4(a)),a.G=P4(a);a.G>0;a.G--){var b=P4(a),c=P4(a),d=P4(a);b&4&&(b&3)===this.track&&(this.track===0||this.track===1)&&(b=this.j,b.j.push({time:a.C,type:this.track,dX:c,eX:d,order:b.j.length}))}zsb(this.j,a);return a.B}return[]};
R4.prototype.reset=function(){this.j.clear()};g.y(S4,r4);g.k=S4.prototype;g.k.e1=function(){g.Nv(this.Wa)};
g.k.Qba=function(){g.Uv(this.element,"ytp-rollup-mode");this.kC(this.Sb,!0)};
g.k.gY=function(){return this.C?this.qa:this.Y};
g.k.hY=function(){return this.C?this.Y:this.qa};
g.k.kC=function(a,b){this.Sb=a;if(this.B.params.ws){for(var c=0,d=0;d<this.K.length&&c<a.length;d++)this.K[d]===a[c]&&c++;c>0&&c<a.length&&(a=this.K.concat(a.slice(c)));this.Kb=this.qa;this.Y=this.qa=0;r4.prototype.kC.call(this,a);Ysb(this,b)}r4.prototype.kC.call(this,a)};g.y(T4,B4);
T4.prototype.Io=function(a,b){var c=[];a=a.split(ztb);for(var d=1;d<a.length;d++){var e=a[d],f=b;if(e!==""&&!Atb.test(e)){var h=Btb.exec(e);if(h&&h.length>=4){var l=$sb(h[1]),m=$sb(h[2])-l;l+=f;var n=(h=h[3])?h.split(" "):[];h={};var p=null;var q="";var r=null,t="";n=g.v(n);for(var u=n.next();!u.done;u=n.next())if(u=u.value.split(":"),u.length===2){var w=u[1];switch(u[0]){case "line":u=w.split(",");u[0].endsWith("%")&&(p=u[0],h.Uo=Number.parseInt(p,10),u.length===2&&(q=u[1].trim()));break;case "position":u=
w.split(",");r=u[0];h.pk=Number.parseInt(r,10);u.length===2&&(t=u[1].trim());break;case "align":switch(w){case "start":h.textAlign=0;break;case "middle":h.textAlign=2;break;case "end":h.textAlign=1}}}p||q||(q="end");if(!r)switch(h.textAlign){case 0:h.pk=0;break;case 1:h.pk=100;break;case 2:h.pk=50}if(h.textAlign!=null){p=0;switch(q){case "center":p+=3;break;case "end":p+=6;break;default:p+=0}switch(t){case "line-left":p+=0;break;case "center":p+=1;break;case "line-right":p+=2;break;default:switch(h.textAlign){case 0:p+=
0;break;case 2:p+=1;break;case 1:p+=2}}q=p<0||p>8?7:p;h.mm=q}e=e.substring(Btb.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");t=h;h=e;e={};if(h.indexOf("<")<0&&h.indexOf("&")<0)f=atb(l,m,5,t),m=new A4(l,m,5,f.id,h,!1,g.gd(e)?void 0:e),c.push(f),c.push(m),f.j.push(m);else for(q=h.split(Ctb),q.length===1?(h=5,t=atb(l,m,h,t)):(p=h=6,t=Object.assign({ut:32},t),t=new C4(l,m,p,"_"+D4++,t)),c.push(t),p=l,r=0;r<q.length;r++)n=q[r],r%2===0?(u=g.e2("<html>"+n+"</html>"),u.getElementsByTagName("parsererror").length?
(w=u.createElement("span"),w.appendChild(u.createTextNode(n))):w=u.firstChild,Zsb(this,p,m-(p-l),h,t,r>0,w,e,c)):p=$sb(n)+f}Btb.lastIndex=0}}return c};
var Atb=/^NOTE/,ztb=/(?:\r\n|\r|\n){2,}/,Btb=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),Ctb=RegExp("<((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})>");g.EX.iK(T4,{Io:"wvppt"});g.y(U4,g.I);
U4.prototype.Io=function(a,b,c,d){c=c||0;d=d||0;if(this.B&&a){a:{var e=d,f=dtb(this,a,c),h=[];try{for(var l=g.v(f),m=l.next();!m.done;m=l.next()){var n=m.value,p=n.trackData,q=n.CT;h=typeof p!=="string"?h.concat(etb(this,b,p,q,e)):p.substring(0,6)==="WEBVTT"?h.concat(ftb(this,p,q)):h.concat(htb(this,b,p,q))}var r=h;break a}catch(t){g.uE(t);this.clear();r=[];break a}r=void 0}if(r.length!==0)return r}a=btb(a);if(!a)return[];try{return typeof a!=="string"?etb(this,b,a,c,d):a.substring(0,6)==="WEBVTT"?
ftb(this,a,c):htb(this,b,a,c)}catch(t){return g.uE(t),this.clear(),[]}};
U4.prototype.clear=function(){this.j&&this.j.dispose();this.j=null};
U4.prototype.reset=function(){this.j&&this.j.reset()};
U4.prototype.xa=function(){g.I.prototype.xa.call(this);this.clear()};var c5={windowColor:"#080808",windowOpacity:0,textAlign:2,mm:7,pk:50,Uo:100,isDefault:!0,Re:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.y(V4,g.pV);g.k=V4.prototype;g.k.xa=function(){if(this.D||this.Fa){var a=this.J.Je();a&&!a.Ma()&&a.Ez()}else wtb(this,!1);g.pV.prototype.xa.call(this)};
g.k.sT=function(){return this.X.L("html5_honor_caption_availabilities_in_audio_track")&&!this.bb};
g.k.Vu=function(){if(this.Wa)return this.D||this.Fa;var a=this.getAudioTrack();if(this.sT()){if(!a.captionTracks.length)return!1;if(!this.j)return!0}a=Vrb(a,g.MR(this.X));return a==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?!0:a==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"?W4(this):ltb(this)||W4(this)?!0:mtb(this)};
g.k.load=function(){var a=this;g.pV.prototype.load.call(this);this.N=this.getAudioTrack();this.j?this.B&&(this.eb.clear(),this.D?qtb(this,!0):this.player.getPresentingPlayerType()!==3&&this.j.yu(this.B,"json3",function(b,c,d,e){if(b){var f;rtb(a,(f=a.B)!=null?f:void 0);a.j.sS()&&(a.Ha=[],a.J.qf("captions"),o4(a.La),a.eb.reset());if(a.videoData.Sf){var h;d=((h=d)!=null?h:0)+a.videoData.Sf}b=a.eb.Io(b,c,d,e);if(a.fb)for(c=g.v(b),e=c.next();!e.done;e=c.next())e=e.value,e.C=a.videoData.clientPlaybackNonce,
e.yl=a.videoData.Sf;c=!a.X.L("html5_keep_caption_data_after_seek")&&a.bb;a.player.jf(b,void 0,c);!a.Y||a.Fa||Z4(a)||!a.X.fm||g.CI(a.X)||g.CR(a.X)||g.XF(a.X)||a.X.La==="shortspage"||a.player.isInline()||(g.Ov(a.Na),b=Psb({mm:0,pk:5,Uo:5,ws:2,textAlign:0,Ki:0,lang:"en"}),a.Sa=[b],c=["Click "," for settings"],a.rb||(e=new g.SE(g.Bya()),g.M(a,e),a.rb=e.element),e=b.end-b.start,(f=g.cS(a.B))&&a.Sa.push(new A4(b.start,e,0,b.id,f)),a.Sa.push(new A4(b.start,e,0,b.id,c[0]),new A4(b.start,e,0,b.id,a.rb,!0),
new A4(b.start,e,0,b.id,c[1],!0)),a.player.jf(a.Sa),g.Mv(a.Na));!a.Y||a.Fa||Z4(a)||(g.MR(a.X)?a5(a,!0):b5(a,!0),a.N&&(a.N.D=a.B),a.player.Yo());a.Y=!1}}),this.D||this.Fa||Z4(this)||this.player.Dc("captionschanged",g.dS(this.B))):(this.j=ntb(this),g.M(this,this.j),this.j.WA(function(){ptb(a)}))};
g.k.unload=function(){this.D&&this.B?qtb(this,!1):(this.Na&&g.Ov(this.Na),this.player.qf("captions"),this.Ha=[],this.j&&this.j.Ls(),this.eb.clear(),this.Z&&this.player.jf(this.Z),this.cU());g.pV.prototype.unload.call(this);this.player.Yo();this.player.Dc("captionschanged",{})};
g.k.create=function(){this.Vu()&&this.load();var a;a:{var b,c,d;if(this.X.L("web_player_nitrate_promo_tooltip")&&((b=this.videoData.getPlayerResponse())==null?0:(c=b.captions)==null?0:(d=c.playerCaptionsTracklistRenderer)==null?0:d.enableTouchCaptionsNitrate)){var e,f;if(b=(a=this.videoData.getPlayerResponse())==null?void 0:(e=a.captions)==null?void 0:(f=e.playerCaptionsTracklistRenderer)==null?void 0:f.captionTracks)for(a=g.v(b),e=a.next();!e.done;e=a.next())if(e=e.value,e.kind==="asr"&&e.languageCode===
"en"){a=!0;break a}}a=!1}a&&this.J.publish("showpromotooltip",this.K.element)};
g.k.wca=function(){for(var a=this.J.Je().Ib().textTracks,b=null,c=0;c<a.length;c++)if(a[c].mode==="showing")a:{b=g.qV(this.j.B,!0);for(var d=0;d<b.length;d++)if(b[d].toString()===a[c].id){b=b[d];break a}b=null}(this.loaded?this.B:null)!==b&&$4(this,b,!0)};
g.k.Qea=function(){!this.B&&this.D||this.unload()};
g.k.onCueRangeEnter=function(a){this.Ha.push(a);o4(this.La)};
g.k.onCueRangeExit=function(a){g.Hb(this.Ha,a);this.j instanceof q4&&this.j.K&&this.player.Qo([a]);o4(this.La)};
g.k.getCaptionWindowContainerId=function(){return this.K.element.id};
g.k.qda=function(){vtb(this,this.Sa);this.Sa=null};
g.k.ZT=function(){var a=this;if(!this.Gb||!this.D){this.La.stop();g.eba(this.Va);this.Ha.sort(g.ZCa);var b=this.Ha;if(this.Z){var c=g.Tt(b,function(f){return this.Z.indexOf(f)===-1},this);
c.length&&(b=c)}b=g.v(b);for(c=b.next();!c.done;c=b.next())ttb(this,c.value);b=g.v(Object.entries(this.ra));var d=b.next();for(c={};!d.done;c={yA:void 0,Dp:void 0},d=b.next()){var e=g.v(d.value);d=e.next().value;e=e.next().value;c.yA=d;c.Dp=e;this.Va[c.yA]?(c.Dp.element.parentNode||(c.Dp instanceof S4||c.Dp instanceof N4||g.Yc(this.ra,function(f){return function(h,l){l!==f.yA&&h.B.params.mm===f.Dp.B.params.mm&&h.B.params.pk===f.Dp.B.params.pk&&h.B.params.Uo===f.Dp.B.params.Uo&&(h.dispose(),delete a.ra[l]);
return l===f.yA}}(c),this),this.K.element.appendChild(c.Dp.element)),c.Dp.kC(this.Va[c.yA])):(c.Dp.dispose(),delete this.ra[c.yA])}}};
g.k.wda=function(){jtb(this,{},!0);this.player.Dc("captionssettingschanged")};
g.k.Z8=function(){var a=c5.Re;a={background:a.background,backgroundOpacity:a.backgroundOpacity,charEdgeStyle:a.charEdgeStyle,color:a.color,fontFamily:a.fontFamily,fontSizeIncrement:a.fontSizeIncrement,fontStyle:a.bold&&a.italic?3:a.bold?1:a.italic?2:0,textOpacity:a.textOpacity,windowColor:c5.windowColor,windowOpacity:c5.windowOpacity};var b=bsb()||{};b.background!=null&&(a.background=b.background);b.backgroundOverride!=null&&(a.backgroundOverride=b.backgroundOverride);b.backgroundOpacity!=null&&(a.backgroundOpacity=
b.backgroundOpacity);b.backgroundOpacityOverride!=null&&(a.backgroundOpacityOverride=b.backgroundOpacityOverride);b.charEdgeStyle!=null&&(a.charEdgeStyle=b.charEdgeStyle);b.charEdgeStyleOverride!=null&&(a.charEdgeStyleOverride=b.charEdgeStyleOverride);b.color!=null&&(a.color=b.color);b.colorOverride!=null&&(a.colorOverride=b.colorOverride);b.fontFamily!=null&&(a.fontFamily=b.fontFamily);b.fontFamilyOverride!=null&&(a.fontFamilyOverride=b.fontFamilyOverride);b.fontSizeIncrement!=null&&(a.fontSizeIncrement=
b.fontSizeIncrement);b.fontSizeIncrementOverride!=null&&(a.fontSizeIncrementOverride=b.fontSizeIncrementOverride);b.fontStyle!=null&&(a.fontStyle=b.fontStyle);b.fontStyleOverride!=null&&(a.fontStyleOverride=b.fontStyleOverride);b.textOpacity!=null&&(a.textOpacity=b.textOpacity);b.textOpacityOverride!=null&&(a.textOpacityOverride=b.textOpacityOverride);b.windowColor!=null&&(a.windowColor=b.windowColor);b.windowColorOverride!=null&&(a.windowColorOverride=b.windowColorOverride);b.windowOpacity!=null&&
(a.windowOpacity=b.windowOpacity);b.windowOpacityOverride!=null&&(a.windowOpacityOverride=b.windowOpacityOverride);return a};
g.k.X2=function(a,b){var c={};Object.assign(c,bsb());Object.assign(c,a);jtb(this,c,b);this.player.Dc("captionssettingschanged")};
g.k.cU=function(){!this.D&&this.loaded&&(g.Uc(this.ra,function(a,b){a.dispose();delete this.ra[b]},this),this.ZT())};
g.k.Sh=function(a,b){switch(a){case "fontSize":if(isNaN(b))break;var c=g.ze(b,-2,4);this.X2({fontSizeIncrement:c});return c;case "reload":b&&!this.D&&$4(this,this.B,!0);break;case "stickyLoading":b!==void 0&&this.X.N&&(g.MR(this.X)?a5(this,!!b):b5(this,!!b));break;case "track":if(!this.j)return{};if(b){if(this.D)break;if(!g.db(b))break;if(g.gd(b)){$4(this,null,!0);break}a=g.qV(this.j.B,!0);for(var d=0;d<a.length;d++){var e=a[d];e.languageCode!==b.languageCode||c&&(e.languageName!==b.languageName||
(e.captionId||"")!==(b.captionId||"")||g.cS(e)!==b.displayName)||(c=b.translationLanguage?Wrb(e,b.translationLanguage):e)}this.DM(b.position);!c||c===this.B&&this.loaded||(b=g.$Pa(),a=g.eS(c),b.length&&a===b[b.length-1]||(b.push(a),g.FB("yt-player-caption-language-preferences",b)),g.MR(this.X)&&!this.J.isInline()&&g.FB("yt-player-caption-sticky-language",a,2592E3),$4(this,c,!0))}else return this.loaded&&this.B&&!Z4(this)?g.dS(this.B):{};return"";case "tracklist":return this.j?g.es(g.qV(this.j.B,!(!b||
!b.includeAsr)),function(f){return g.dS(f)}):[];
case "translationLanguages":return this.j?this.j.D.map(function(f){return Object.assign({},f)}):[];
case "sampleSubtitles":this.D||b===void 0||wtb(this,!!b);break;case "sampleSubtitlesCustomized":this.D||wtb(this,!!b,b);break;case "recommendedTranslationLanguages":return g.$Pa();case "defaultTranslationSourceTrackIndices":return this.j?this.j.N:[]}};
g.k.getOptions=function(){var a="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.X.N&&a.push("stickyLoading");return a};
g.k.Fr=function(){var a=this.B;if(this.X.L("html5_cue_ranges_based_caption_vss")&&!this.J.XJ("captions"))return{};if(this.X.L("html5_modify_caption_vss_logging")){var b;return(a=(b=this.videoData.vD)!=null?b:null)?{cc:g.VVa(a)}:{}}return a?(b=a.vssId,a.translationLanguage&&b&&(b="t"+b+"."+g.eS(a)),{cc:b}):{}};
g.k.Cea=function(){this.isSubtitlesOn()?(g.MR(this.X)?a5(this,!1):b5(this,!1),rtb(this),this.unload(),W4(this,!0)&&$4(this,X4(this),!1)):this.z2()};
g.k.z2=function(){this.isSubtitlesOn()||$4(this,Z4(this)||!this.B?Y4(this,!0):this.B,!0)};
g.k.isSubtitlesOn=function(){return!!this.loaded&&!!this.B&&!Z4(this)};
g.k.naa=function(){var a=Z4(this);W4(this,a)?$4(this,this.getAudioTrack().j,!1):this.videoData.captionTracks.length&&(this.loaded&&this.unload(),this.sT()&&(this.Y=!1,this.B=null,this.j&&(this.j.dispose(),this.j=null)),this.Vu()&&(a?$4(this,Y4(this),!1):this.load()))};
g.k.DM=function(a){a&&(this.qa={top:a.top,right:a.right,bottom:a.bottom,left:a.left,width:1-a.left-a.right,height:1-a.top-a.bottom},this.K.element.style.top=this.qa.top*100+"%",this.K.element.style.left=this.qa.left*100+"%",this.K.element.style.width=this.qa.width*100+"%",this.K.element.style.height=this.qa.height*100+"%",this.K.element.style.position="absolute",a=utb(this))&&(this.K.element.style.width=a.width+"px",this.K.element.style.height=a.height+"px")};
g.k.onVideoDataChange=function(a,b){a==="newdata"&&(this.videoData=b,this.loaded&&this.unload(),this.Y=!1,this.B=null,this.j&&(this.j.dispose(),this.j=null,this.player.Dc("captionschanged",{})),this.Vu()&&this.load())};
g.k.getAudioTrack=function(){return this.fb&&this.player.getPresentingPlayerType()===2?this.videoData.Nk:this.player.getAudioTrack()};
g.k.Xaa=function(){var a=this.J.Je();a&&!a.Ma()&&a.Ez();this.J.isFullscreen()?(this.D=this.Wa=!0,this.loaded&&ptb(this)):(this.Wa=this.X.controlsType==="3",this.D=itb(this));$4(this,this.B)};
g.k.WM=function(){var a,b,c,d=(a=this.videoData.getPlayerResponse())==null?void 0:(b=a.captions)==null?void 0:(c=b.playerCaptionsTracklistRenderer)==null?void 0:c.openTranscriptCommand;d&&this.player.ib("innertubeCommand",d)};
g.EX.iK(V4,{ZT:"smucd"});g.oV("captions",V4);})(_yt_player);
